/*
 Copyright 2005-2014 the original author or authors.
 Licensed under the Apache License, Version 2.0 (the "License").
 You may obtain a copy of the License at
      http://www.apache.org/licenses/LICENSE-2.0
*/
(function(){var u=Handlebars.template,v=Handlebars.templates=Handlebars.templates||{};v._logo=u(function(c,a,e,d,b){function g(a,e){var c,f;return c=""+("\n                <a onclick=\"window.open('"+h((f=(f=a&&a.page,null==f||!1===f?f:f.mibewHost),typeof f===m?f.apply(a):f))+'\');return false;" href="'+h((f=(f=a&&a.page,null==f||!1===f?f:f.mibewHost),typeof f===m?f.apply(a):f))+'">\n                    <img src="'+h((f=(f=(f=a&&a.page,null==f||!1===f?f:f.company),null==f||!1===f?f:f.chatLogoURL),
typeof f===m?f.apply(a):f))+'" alt=""/>\n                </a>\n            ')}function k(a,e){var c,f;return c=""+('\n                <img src="'+h((f=(f=(f=a&&a.page,null==f||!1===f?f:f.company),null==f||!1===f?f:f.chatLogoURL),typeof f===m?f.apply(a):f))+'" alt=""/>\n            ')}function l(a,e){var c,f;return c=""+("\n                <a onclick=\"window.open('"+h((f=(f=a&&a.page,null==f||!1===f?f:f.mibewHost),typeof f===m?f.apply(a):f))+'\');return false;" href="'+h((f=(f=a&&a.page,null==f||
!1===f?f:f.mibewHost),typeof f===m?f.apply(a):f))+'">\n                    <img src="'+h((f=(f=a&&a.page,null==f||!1===f?f:f.tplRoot),typeof f===m?f.apply(a):f))+'/images/default-logo.png" alt=""/>\n                </a>\n            ')}function t(a,e){var c,f;return c=""+('\n                <img src="'+h((f=(f=a&&a.page,null==f||!1===f?f:f.tplRoot),typeof f===m?f.apply(a):f))+'/images/default-logo.png" alt=""/>\n            ')}this.compilerInfo=[4,">= 1.0.0"];e=this.merge(e,c.helpers);b=b||{};var n,
m="function",h=this.escapeExpression,s=this;c='\n<div id="top2">\n    <div id="logo">\n        ';if((n=e["if"].call(a,(n=(n=a&&a.page,null==n||!1===n?n:n.company),null==n||!1===n?n:n.chatLogoURL),{hash:{},inverse:s.program(6,function(a,c){var b,f;b="\n            ";if((f=e["if"].call(a,(f=a&&a.page,null==f||!1===f?f:f.mibewHost),{hash:{},inverse:s.program(9,t,c),fn:s.program(7,l,c),data:c}))||0===f)b+=f;return b+"\n        "},b),fn:s.program(1,function(a,c){var b,f;b="\n            ";if((f=e["if"].call(a,
(f=a&&a.page,null==f||!1===f?f:f.mibewHost),{hash:{},inverse:s.program(4,k,c),fn:s.program(2,g,c),data:c}))||0===f)b+=f;return b+"\n        "},b),data:b}))||0===n)c+=n;return c+='\n        &nbsp;\n        <div id="page-title">'+h((n=(n=a&&a.page,null==n||!1===n?n:n.title),typeof n===m?n.apply(a):n))+'</div>\n        <div class="clear">&nbsp;</div>\n    </div>\n</div>'});v["chat/avatar"]=u(function(c,a,e,d,b){this.compilerInfo=[4,">= 1.0.0"];e=this.merge(e,c.helpers);b=b||{};var g=this.escapeExpression;
return(c=e["if"].call(a,a&&a.imageLink,{hash:{},inverse:this.program(3,function(a,e){return'<div class="default-avatar"></div>'},b),fn:this.program(1,function(a,c){var b,d;b='<img src="';(d=e.imageLink)?d=d.call(a,{hash:{},data:c}):(d=a&&a.imageLink,d="function"===typeof d?d.call(a,{hash:{},data:c}):d);return b+=g(d)+'" border="0" alt="" />'},b),data:b}))||0===c?c:""});v["chat/controls/close"]=u(function(c,a,e,d,b){this.compilerInfo=[4,">= 1.0.0"];e=this.merge(e,c.helpers);b=b||{};var g,k;c=e.helperMissing;
d=this.escapeExpression;return a=""+('<div class="tpl-image" title="'+d((g=e.l10n||a&&a.l10n,k={hash:{},data:b},g?g.call(a,"Close chat",k):c.call(a,"l10n","Close chat",k)))+'"></div>')});v["chat/controls/history"]=u(function(c,a,e,d,b){this.compilerInfo=[4,">= 1.0.0"];e=this.merge(e,c.helpers);b=b||{};var g,k;c=e.helperMissing;d=this.escapeExpression;return a=""+('<div class="tpl-image" title="'+d((g=e.l10n||a&&a.l10n,k={hash:{},data:b},g?g.call(a,"Visit history",k):c.call(a,"l10n","Visit history",
k)))+'"></div>')});v["chat/controls/redirect"]=u(function(c,a,e,d,b){this.compilerInfo=[4,">= 1.0.0"];e=this.merge(e,c.helpers);b=b||{};var g,k=e.helperMissing,l=this.escapeExpression;return(g=e["if"].call(a,(g=a&&a.user,null==g||!1===g?g:g.canPost),{hash:{},inverse:this.noop,fn:this.program(1,function(a,c){var b,d,s;return b=""+('\n<div class="tpl-image" title="'+l((d=e.l10n||a&&a.l10n,s={hash:{},data:c},d?d.call(a,"Redirect visitor to another operator",s):k.call(a,"l10n","Redirect visitor to another operator",
s)))+'"></div>\n')},b),data:b}))||0===g?g:""});v["chat/controls/refresh"]=u(function(c,a,e,d,b){this.compilerInfo=[4,">= 1.0.0"];e=this.merge(e,c.helpers);b=b||{};var g,k;c=e.helperMissing;d=this.escapeExpression;return a=""+('<div class="tpl-image" title="'+d((g=e.l10n||a&&a.l10n,k={hash:{},data:b},g?g.call(a,"Refresh",k):c.call(a,"l10n","Refresh",k)))+'"></div>')});v["chat/controls/secure_mode"]=u(function(c,a,e,d,b){this.compilerInfo=[4,">= 1.0.0"];this.merge(e,c.helpers);return'<div class="tpl-image" title="SSL"></div>'});
v["chat/controls/send_mail"]=u(function(c,a,e,d,b){this.compilerInfo=[4,">= 1.0.0"];e=this.merge(e,c.helpers);b=b||{};var g,k;c=e.helperMissing;d=this.escapeExpression;return a=""+('<div class="tpl-image" title="'+d((g=e.l10n||a&&a.l10n,k={hash:{},data:b},g?g.call(a,"Send chat history by e-mail",k):c.call(a,"l10n","Send chat history by e-mail",k)))+'"></div>')});v["chat/controls/sound"]=u(function(c,a,e,d,b){this.compilerInfo=[4,">= 1.0.0"];e=this.merge(e,c.helpers);b=b||{};var g=e.helperMissing,
k=this.escapeExpression;return(c=e["if"].call(a,a&&a.enabled,{hash:{},inverse:this.program(3,function(a,c){var b,d,h;return b=""+('\n    <div class="tpl-image sound-control-off" title="'+k((d=e.l10n||a&&a.l10n,h={hash:{},data:c},d?d.call(a,"Turn on sound",h):g.call(a,"l10n","Turn on sound",h)))+'"></div>\n')},b),fn:this.program(1,function(a,c){var b,d,h;return b=""+('\n    <div class="tpl-image sound-control-on" title="'+k((d=e.l10n||a&&a.l10n,h={hash:{},data:c},d?d.call(a,"Turn off sound",h):g.call(a,
"l10n","Turn off sound",h)))+'"></div>\n')},b),data:b}))||0===c?c:""});v["chat/controls/user_name"]=u(function(c,a,e,d,b){function g(a,c){var b,d,f,h;return b=""+('\n        <div class="user-name-control-input-bg"><input id="user-name-control-input" type="text" size="12" value="'+n((d=(d=a&&a.user,null==d||!1===d?d:d.name),typeof d===t?d.apply(a):d))+'" class="username" /></div>\n        <a href="javascript:void(0)" class="user-name-control-set tpl-image" title="'+n((f=e.l10n||a&&a.l10n,h={hash:{},
data:c},f?f.call(a,"Change name",h):m.call(a,"l10n","Change name",h)))+'"></a>\n    ')}function k(a,c){var b,d,f,h;return b=""+('\n        <a href="javascript:void(0)" title="'+n((f=e.l10n||a&&a.l10n,h={hash:{},data:c},f?f.call(a,"Change name",h):m.call(a,"l10n","Change name",h)))+'">'+n((d=(d=a&&a.user,null==d||!1===d?d:d.name),typeof d===t?d.apply(a):d))+'</a>\n        <a class="user-name-control-change tpl-image" title="'+n((f=e.l10n||a&&a.l10n,h={hash:{},data:c},f?f.call(a,"Change name",h):m.call(a,
"l10n","Change name",h)))+'"></a>\n    ')}this.compilerInfo=[4,">= 1.0.0"];e=this.merge(e,c.helpers);b=b||{};var l,t="function",n=this.escapeExpression,m=e.helperMissing,h=this;return(l=e["if"].call(a,(l=a&&a.user,null==l||!1===l?l:l.canChangeName),{hash:{},inverse:h.program(6,function(a,c){var b,d,f,h;return b=""+("\n"+n((f=e.l10n||a&&a.l10n,h={hash:{},data:c},f?f.call(a,"You are",h):m.call(a,"l10n","You are",h)))+"&nbsp;"+n((d=(d=a&&a.user,null==d||!1===d?d:d.name),typeof d===t?d.apply(a):d))+"\n")},
b),fn:h.program(1,function(a,c){var d,b,f;d=""+('\n    <span class="user-name-control-prefix">'+n((b=e.l10n||a&&a.l10n,f={hash:{},data:c},b?b.call(a,"You are",f):m.call(a,"l10n","You are",f)))+"</span>\n    ");if((b=e["if"].call(a,a&&a.nameInput,{hash:{},inverse:h.program(4,k,c),fn:h.program(2,g,c),data:c}))||0===b)d+=b;return d+"\n"},b),data:b}))||0===l?l:""});v["chat/layout"]=u(function(c,a,e,d,b){this.compilerInfo=[4,">= 1.0.0"];e=this.merge(e,c.helpers);d=this.merge(d,c.partials);b=b||{};var g,
k,l=e.helperMissing,t=this.escapeExpression;c="\n";if((d=this.invokePartial(d._logo,"_logo",a,e,d,b))||0===d)c+=d;c+='\n\n\n<div id="chat-header">\n    <div class="bgc"><div class="bgl"><div class="bgr">\n        \n        <div id="controls-region"></div>\n    </div></div></div>\n</div>\n\n\n<div id="chat">\n    <div class="bgl"><div class="bgr"><div class="sdwbgc"><div class="sdwbgl"><div class="sdwbgr">\n        ';if((d=e.unless.call(a,(d=a&&a.user,null==d||!1===d?d:d.isAgent),{hash:{},inverse:this.noop,
fn:this.program(1,function(a,c){return'\n        <div id="avatar-region"></div>\n        '},b),data:b}))||0===d)c+=d;return c+='\n        \n        <div id="messages-region"></div>\n        \n        <div id="status-region"></div>\n    </div></div></div></div></div>\n</div>\n\n\n<div id="message-form-region"></div>\n\n\n<div id="footer">'+t((g=e.l10n||a&&a.l10n,k={hash:{},data:b},g?g.call(a,"Powered by:",k):l.call(a,"l10n","Powered by:",k)))+' <a id="poweredByLink" href="http://mibew.org" title="Mibew Community" target="_blank">mibew.org</a></div>'});
v["chat/message"]=u(function(c,a,e,d,b){this.compilerInfo=[4,">= 1.0.0"];e=this.merge(e,c.helpers);b=b||{};var g,k,l=this.escapeExpression,t=e.helperMissing;c=""+("<span>"+l((g=e.formatTime||a&&a.formatTime,k={hash:{},data:b},g?g.call(a,a&&a.created,k):t.call(a,"formatTime",a&&a.created,k)))+"</span> \n");if((g=e["if"].call(a,a&&a.name,{hash:{},inverse:this.noop,fn:this.program(1,function(a,c){var b,d;b="<span class='n";(d=e.kindName)?d=d.call(a,{hash:{},data:c}):(d=a&&a.kindName,d="function"===typeof d?
d.call(a,{hash:{},data:c}):d);b+=l(d)+"'>";(d=e.name)?d=d.call(a,{hash:{},data:c}):(d=a&&a.name,d="function"===typeof d?d.call(a,{hash:{},data:c}):d);return b+=l(d)+"</span>: "},b),data:b}))||0===g)c+=g;c+="\n<span class='m";(g=e.kindName)?g=g.call(a,{hash:{},data:b}):(g=a&&a.kindName,g="function"===typeof g?g.call(a,{hash:{},data:b}):g);c+=l(g)+"'>";if((g=e["if"].call(a,a&&a.allowFormatting,{hash:{},inverse:this.program(5,function(a,c){var d,b;return l((d=e.apply||a&&a.apply,b={hash:{},data:c},d?
d.call(a,a&&a.message,"urlReplace, nl2br",b):t.call(a,"apply",a&&a.message,"urlReplace, nl2br",b)))},b),fn:this.program(3,function(a,c){var d,b;return l((d=e.apply||a&&a.apply,b={hash:{},data:c},d?d.call(a,a&&a.message,"urlReplace, nl2br, allowTags",b):t.call(a,"apply",a&&a.message,"urlReplace, nl2br, allowTags",b)))},b),data:b}))||0===g)c+=g;return c+"</span><br/>"});v["chat/message_form"]=u(function(c,a,e,d,b){function g(a,c){var d,b,f;d=""+('\n                <select id="predefined" size="1" class="answer">\n                    <option>'+
n((b=e.l10n||a&&a.l10n,f={hash:{},data:c},b?b.call(a,"Select answer...",f):m.call(a,"l10n","Select answer...",f)))+"</option>\n                ");if((b=e.each.call(a,a&&a.predefinedAnswers,{hash:{},inverse:h.noop,fn:h.program(5,k,c),data:c}))||0===b)d+=b;return d+"\n                </select>\n            "}function k(a,c){var d,b;return d=""+("\n                    <option>"+n((b=a&&a["short"],typeof b===t?b.apply(a):b))+"</option>\n                ")}this.compilerInfo=[4,">= 1.0.0"];e=this.merge(e,
c.helpers);b=b||{};var l,t="function",n=this.escapeExpression,m=e.helperMissing,h=this;c='<div id="message">\n';if((l=e["if"].call(a,(l=a&&a.user,null==l||!1===l?l:l.canPost),{hash:{},inverse:h.noop,fn:h.program(1,function(a,c){return'\n    <div class="bgc"><div class="bgl"><div class="bgr">\n        <textarea id="message-input" class="message" tabindex="0" rows="4" cols="10"></textarea>\n    </div></div></div>\n'},b),data:b}))||0===l)c+=l;c+='\n</div>\n\n<div id="send">\n';if((l=e["if"].call(a,(l=
a&&a.user,null==l||!1===l?l:l.canPost),{hash:{},inverse:h.noop,fn:h.program(3,function(a,c){var d,b,f,w;d='\n    <div id="postmessage">\n        <div id="predefined-wrapper">\n            ';if((b=e["if"].call(a,(b=a&&a.user,null==b||!1===b?b:b.isAgent),{hash:{},inverse:h.noop,fn:h.program(4,g,c),data:c}))||0===b)d+=b;return d+='\n        </div>\n        <a href="javascript:void(0)" id="send-message" title="'+n((f=e.l10n||a&&a.l10n,w={hash:{},data:c},f?f.call(a,"Send message",w):m.call(a,"l10n","Send message",
w)))+'">'+n((f=e.l10n||a&&a.l10n,w={hash:{},data:c},f?f.call(a,"chat.window.send_message_short_and_shortcut",w):m.call(a,"l10n","chat.window.send_message_short_and_shortcut",w)))+"</a>\n    </div>\n"},b),data:b}))||0===l)c+=l;return c+'\n</div>\n<div class="clear"></div>'});v["chat/status/base"]=u(function(c,a,e,d,b){this.compilerInfo=[4,">= 1.0.0"];e=this.merge(e,c.helpers);b=b||{};c=this.escapeExpression;(e=e.title)?a=e.call(a,{hash:{},data:b}):(e=a&&a.title,a="function"===typeof e?e.call(a,{hash:{},
data:b}):e);return c(a)});v["chat/status/message"]=u(function(c,a,e,d,b){this.compilerInfo=[4,">= 1.0.0"];e=this.merge(e,c.helpers);b=b||{};c=this.escapeExpression;(e=e.message)?a=e.call(a,{hash:{},data:b}):(e=a&&a.message,a="function"===typeof e?e.call(a,{hash:{},data:b}):e);return c(a)});v["chat/status/typing"]=u(function(c,a,e,d,b){this.compilerInfo=[4,">= 1.0.0"];e=this.merge(e,c.helpers);b=b||{};var g,k;c=e.helperMissing;d=this.escapeExpression;return d((g=e.l10n||a&&a.l10n,k={hash:{},data:b},
g?g.call(a,"Remote user is typing...",k):c.call(a,"l10n","Remote user is typing...",k)))});v.default_control=u(function(c,a,e,d,b){this.compilerInfo=[4,">= 1.0.0"];e=this.merge(e,c.helpers);b=b||{};d=this.escapeExpression;c="<strong>";(e=e.title)?a=e.call(a,{hash:{},data:b}):(e=a&&a.title,a="function"===typeof e?e.call(a,{hash:{},data:b}):e);return c+=d(a)+"</strong>"});v["invitation/layout"]=u(function(c,a,e,d,b){this.compilerInfo=[4,">= 1.0.0"];this.merge(e,c.helpers);return'<div id="invitation-messages-region"></div>'});
v["leave_message/description"]=u(function(c,a,e,d,b){this.compilerInfo=[4,">= 1.0.0"];e=this.merge(e,c.helpers);b=b||{};var g,k,l;c=e.helperMissing;d=this.escapeExpression;return a=""+('<div class="buttons">\n    <a href="javascript:window.close();" title="'+d((k=e.l10n||a&&a.l10n,l={hash:{},data:b},k?k.call(a,"Close",l):c.call(a,"l10n","Close",l)))+'">\n        <img class="tpl-image iclosewin" src="'+d((g=(g=a&&a.page,null==g||!1===g?g:g.tplRoot),"function"===typeof g?g.apply(a):g))+'/images/free.gif" alt="'+
d((k=e.l10n||a&&a.l10n,l={hash:{},data:b},k?k.call(a,"Close",l):c.call(a,"l10n","Close",l)))+'" />\n    </a>\n</div>\n<div class="messagetxt">'+d((k=e.l10n||a&&a.l10n,l={hash:{},data:b},k?k.call(a,"Sorry. None of the support team is available at the moment. <br/>Please leave a message and someone will get back to you shortly.",l):c.call(a,"l10n","Sorry. None of the support team is available at the moment. <br/>Please leave a message and someone will get back to you shortly.",l)))+"</div>")});v["leave_message/form"]=
u(function(c,a,e,d,b){function g(a,c){var d,b;d='<input type="hidden" name="group" value="';(b=e.groupId)?b=b.call(a,{hash:{},data:c}):(b=a&&a.groupId,b=typeof b===s?b.call(a,{hash:{},data:c}):b);return d+=r(b)+'"/>'}function k(a,c){var b,d;b=""+('\n                        <option value="'+r((d=a&&a.id,typeof d===s?d.apply(a):d))+'" ');if((d=e["if"].call(a,a&&a.selected,{hash:{},inverse:p.noop,fn:p.program(6,l,c),data:c}))||0===d)b+=d;return b+=">"+r((d=a&&a.name,typeof d===s?d.apply(a):d))+"</option>\n                    "}
function l(a,d){return'selected="selected"'}function t(a,d){var c;return(c=e["if"].call(a,a&&a.selected,{hash:{},inverse:p.noop,fn:p.program(9,n,d),data:d}))||0===c?c:""}function n(a,d){var c;return r((c=a&&a.description,typeof c===s?c.apply(a):c))}this.compilerInfo=[4,">= 1.0.0"];e=this.merge(e,c.helpers);b=b||{};var m,h,s="function",r=this.escapeExpression,p=this,q=e.helperMissing;c=""+('<form name="leaveMessageForm" method="post" action="">\n    <input type="hidden" name="style" value="'+r((m=
(m=a&&a.page,null==m||!1===m?m:m.style),typeof m===s?m.apply(a):m))+'"/>\n    <input type="hidden" name="info" value="');(d=e.info)?m=d.call(a,{hash:{},data:b}):(d=a&&a.info,m=typeof d===s?d.call(a,{hash:{},data:b}):d);c+=r(m)+'"/>\n    <input type="hidden" name="referrer" value="';(d=e.referrer)?m=d.call(a,{hash:{},data:b}):(d=a&&a.referrer,m=typeof d===s?d.call(a,{hash:{},data:b}):d);c+=r(m)+'"/>\n    ';if((m=e.unless.call(a,a&&a.groups,{hash:{},inverse:p.noop,fn:p.program(1,function(a,c){var d;
return(d=e["if"].call(a,a&&a.groupId,{hash:{},inverse:p.noop,fn:p.program(2,g,c),data:c}))||0===d?d:""},b),data:b}))||0===m)c+=m;c+='\n\n    <div class="errors"></div>\n\n    <table cellspacing="1" cellpadding="5" border="0" class="form">\n        <tr>\n            <td><strong>'+r((d=e.l10n||a&&a.l10n,h={hash:{},data:b},d?d.call(a,"Your email",h):q.call(a,"l10n","Your email",h)))+':</strong></td>\n            <td><input type="text" name="email" size="50" value="';(d=e.email)?m=d.call(a,{hash:{},data:b}):
(d=a&&a.email,m=typeof d===s?d.call(a,{hash:{},data:b}):d);c+=r(m)+'" class="username"/></td>\n        </tr>\n        <tr>\n            <td><strong>'+r((d=e.l10n||a&&a.l10n,h={hash:{},data:b},d?d.call(a,"Your name",h):q.call(a,"l10n","Your name",h)))+':</strong></td>\n            <td><input type="text" name="name" size="50" value="';(d=e.name)?m=d.call(a,{hash:{},data:b}):(d=a&&a.name,m=typeof d===s?d.call(a,{hash:{},data:b}):d);c+=r(m)+'" class="username"/></td>\n        </tr>\n    ';if((m=e["if"].call(a,
a&&a.groups,{hash:{},inverse:p.noop,fn:p.program(4,function(a,d){var c,b,h,g;c=""+('\n        <tr>\n            <td class="text"><strong>'+r((h=e.l10n||a&&a.l10n,g={hash:{},data:d},h?h.call(a,"Choose Department:",g):q.call(a,"l10n","Choose Department:",g)))+'</strong></td>\n            <td>\n                <select name="group" style="min-width:200px;">\n                    ');if((b=e.each.call(a,a&&a.groups,{hash:{},inverse:p.noop,fn:p.program(5,k,d),data:d}))||0===b)c+=b;c+='\n                </select>\n            </td>\n        </tr>\n        <tr>\n            <td class="text"><strong>'+
r((h=e.l10n||a&&a.l10n,g={hash:{},data:d},h?h.call(a,"Department description:",g):q.call(a,"l10n","Department description:",g)))+'</strong></td>\n            <td class="text" id="groupDescription">\n                ';if((b=e.each.call(a,a&&a.groups,{hash:{},inverse:p.noop,fn:p.program(8,t,d),data:d}))||0===b)c+=b;return c+"\n            </td>\n        </tr>\n    "},b),data:b}))||0===m)c+=m;c+="\n        <tr>\n            <td><strong>"+r((d=e.l10n||a&&a.l10n,h={hash:{},data:b},d?d.call(a,"Message",
h):q.call(a,"l10n","Message",h)))+':</strong></td>\n            <td valign="top">\n                <textarea name="message" tabindex="0" cols="40" rows="5">';(d=e.message)?m=d.call(a,{hash:{},data:b}):(d=a&&a.message,m=typeof d===s?d.call(a,{hash:{},data:b}):d);c+=r(m)+"</textarea>\n            </td>\n        </tr>\n    ";if((m=e["if"].call(a,a&&a.showCaptcha,{hash:{},inverse:p.noop,fn:p.program(11,function(a,c){return'\n        <tr>\n            <td><img id="captcha-img" src="captcha"/></td>\n            <td><input type="text" name="captcha" size="50" maxlength="15" value="" class="username"/></td>\n        </tr>\n    '},
b),data:b}))||0===m)c+=m;return c+='\n    </table>\n    <a href="javascript:void(0);" class="but" id="send-message">'+r((d=e.l10n||a&&a.l10n,h={hash:{},data:b},d?d.call(a,"Send",h):q.call(a,"l10n","Send",h)))+'</a>\n    <div class="clear">&nbsp;</div>\n</form>\n<div id="ajax-loader"><img src="'+r((m=(m=a&&a.page,null==m||!1===m?m:m.tplRoot),typeof m===s?m.apply(a):m))+'/images/ajax-loader.gif" alt="Loading..." /></div>'});v["leave_message/layout"]=u(function(c,a,e,d,b){this.compilerInfo=[4,">= 1.0.0"];
e=this.merge(e,c.helpers);d=this.merge(d,c.partials);b=b||{};c="\n";if((a=this.invokePartial(d._logo,"_logo",a,e,d,b))||0===a)c+=a;return c+'\n\n\n<div id="headers">\n    <div class="wndb"><div class="wndl"><div class="wndr"><div class="wndt"><div class="wndtl"><div class="wndtr"><div class="wndbl"><div class="wndbr" id="description-region">\n    </div></div></div></div></div></div></div></div>\n</div>\n\n\n<div id="content-wrapper"></div>'});v["leave_message/sent_description"]=u(function(c,a,e,d,
b){this.compilerInfo=[4,">= 1.0.0"];e=this.merge(e,c.helpers);b=b||{};var g,k,l;c=e.helperMissing;d=this.escapeExpression;return a=""+('<div class="buttons">\n        <a href="javascript:window.close();" title="'+d((k=e.l10n||a&&a.l10n,l={hash:{},data:b},k?k.call(a,"Close...",l):c.call(a,"l10n","Close...",l)))+'">\n            <img class="tpl-image iclosewin" src="'+d((g=(g=a&&a.page,null==g||!1===g?g:g.tplRoot),"function"===typeof g?g.apply(a):g))+'/images/free.gif" alt="'+d((k=e.l10n||a&&a.l10n,
l={hash:{},data:b},k?k.call(a,"Close...",l):c.call(a,"l10n","Close...",l)))+'" />\n        </a>\n</div>\n<div class="messagetxt">'+d((k=e.l10n||a&&a.l10n,l={hash:{},data:b},k?k.call(a,"Thank you for your message. We'll answer your query by email as soon as possible.",l):c.call(a,"l10n","Thank you for your message. We'll answer your query by email as soon as possible.",l)))+"</div>")});v.message=u(function(c,a,e,d,b){this.compilerInfo=[4,">= 1.0.0"];e=this.merge(e,c.helpers);b=b||{};var g,k,l=this.escapeExpression,
t=e.helperMissing;c=""+("<span>"+l((g=e.formatTime||a&&a.formatTime,k={hash:{},data:b},g?g.call(a,a&&a.created,k):t.call(a,"formatTime",a&&a.created,k)))+"</span>\n");if((g=e["if"].call(a,a&&a.name,{hash:{},inverse:this.noop,fn:this.program(1,function(a,c){var d,b;d="<span class='n";(b=e.kindName)?b=b.call(a,{hash:{},data:c}):(b=a&&a.kindName,b="function"===typeof b?b.call(a,{hash:{},data:c}):b);d+=l(b)+"'>";(b=e.name)?b=b.call(a,{hash:{},data:c}):(b=a&&a.name,b="function"===typeof b?b.call(a,{hash:{},
data:c}):b);return d+=l(b)+"</span>: "},b),data:b}))||0===g)c+=g;c+="\n<span class='m";(g=e.kindName)?g=g.call(a,{hash:{},data:b}):(g=a&&a.kindName,g="function"===typeof g?g.call(a,{hash:{},data:b}):g);c+=l(g)+"'>";if((g=e["if"].call(a,a&&a.allowFormatting,{hash:{},inverse:this.program(5,function(a,c){var d,b;return l((d=e.apply||a&&a.apply,b={hash:{},data:c},d?d.call(a,a&&a.message,"urlReplace, nl2br",b):t.call(a,"apply",a&&a.message,"urlReplace, nl2br",b)))},b),fn:this.program(3,function(a,d){var b,
c;return l((b=e.apply||a&&a.apply,c={hash:{},data:d},b?b.call(a,a&&a.message,"urlReplace, nl2br, allowTags",c):t.call(a,"apply",a&&a.message,"urlReplace, nl2br, allowTags",c)))},b),data:b}))||0===g)c+=g;return c+"</span><br/>"});v["survey/form"]=u(function(c,a,e,d,b){function g(a,b){var c,d;c='<input type="hidden" name="group" value="';(d=e.groupId)?d=d.call(a,{hash:{},data:b}):(d=a&&a.groupId,d=typeof d===r?d.call(a,{hash:{},data:b}):d);return c+=p(d)+'"/>'}function k(a,d){var c,b;c=""+('\n                        <option value="'+
p((b=a&&a.id,typeof b===r?b.apply(a):b))+'" ');if((b=e["if"].call(a,a&&a.selected,{hash:{},inverse:q.noop,fn:q.program(10,l,d),data:d}))||0===b)c+=b;c+=">"+p((b=a&&a.name,typeof b===r?b.apply(a):b));if((b=e.unless.call(a,a&&a.online,{hash:{},inverse:q.noop,fn:q.program(12,t,d),data:d}))||0===b)c+=b;return c+"</option>\n                    "}function l(a,b){return'selected="selected"'}function t(a,b){return" (offline)"}function n(a,b){var d;return(d=e["if"].call(a,a&&a.selected,{hash:{},inverse:q.noop,
fn:q.program(15,m,b),data:b}))||0===d?d:""}function m(a,b){var d;return p((d=a&&a.description,typeof d===r?d.apply(a):d))}this.compilerInfo=[4,">= 1.0.0"];e=this.merge(e,c.helpers);b=b||{};var h,s,r="function",p=this.escapeExpression,q=this,f=e.helperMissing;c=""+('<form name="surveyForm" method="post" action="">\n    <input type="hidden" name="style" value="'+p((h=(h=a&&a.page,null==h||!1===h?h:h.style),typeof h===r?h.apply(a):h))+'"/>\n    <input type="hidden" name="info" value="');(d=e.info)?h=
d.call(a,{hash:{},data:b}):(d=a&&a.info,h=typeof d===r?d.call(a,{hash:{},data:b}):d);c+=p(h)+'"/>\n    <input type="hidden" name="referrer" value="';(d=e.referrer)?h=d.call(a,{hash:{},data:b}):(d=a&&a.referrer,h=typeof d===r?d.call(a,{hash:{},data:b}):d);c+=p(h)+'"/>\n    <input type="hidden" name="survey" value="on"/>\n    ';if((h=e.unless.call(a,a&&a.showEmail,{hash:{},inverse:q.noop,fn:q.program(1,function(a,b){var d,c;d='<input type="hidden" name="email" value="';(c=e.email)?c=c.call(a,{hash:{},
data:b}):(c=a&&a.email,c=typeof c===r?c.call(a,{hash:{},data:b}):c);return d+=p(c)+'"/>'},b),data:b}))||0===h)c+=h;c+="\n    ";if((h=e.unless.call(a,a&&a.groups,{hash:{},inverse:q.noop,fn:q.program(3,function(a,b){var d;return(d=e["if"].call(a,a&&a.groupId,{hash:{},inverse:q.noop,fn:q.program(4,g,b),data:b}))||0===d?d:""},b),data:b}))||0===h)c+=h;c+="\n    ";if((h=e.unless.call(a,a&&a.showMessage,{hash:{},inverse:q.noop,fn:q.program(6,function(a,d){var b,c;b='<input type="hidden" name="message" value="';
(c=e.message)?c=c.call(a,{hash:{},data:d}):(c=a&&a.message,c=typeof c===r?c.call(a,{hash:{},data:d}):c);return b+=p(c)+'"/>'},b),data:b}))||0===h)c+=h;c+='\n\n    <div class="errors"></div>\n\n    <table class="form">\n    ';if((h=e["if"].call(a,a&&a.groups,{hash:{},inverse:q.noop,fn:q.program(8,function(a,b){var d,c,g,h;d=""+("\n        <tr>\n            <td><strong>"+p((g=e.l10n||a&&a.l10n,h={hash:{},data:b},g?g.call(a,"Choose Department:",h):f.call(a,"l10n","Choose Department:",h)))+'</strong></td>\n            <td>\n                <select name="group">\n                    ');
if((c=e.each.call(a,a&&a.groups,{hash:{},inverse:q.noop,fn:q.program(9,k,b),data:b}))||0===c)d+=c;d+="\n                </select>\n            </td>\n        </tr>\n        <tr>\n            <td><strong>"+p((g=e.l10n||a&&a.l10n,h={hash:{},data:b},g?g.call(a,"Department description:",h):f.call(a,"l10n","Department description:",h)))+'</strong></td>\n            <td id="groupDescription">';if((c=e.each.call(a,a&&a.groups,{hash:{},inverse:q.noop,fn:q.program(14,n,b),data:b}))||0===c)d+=c;return d+"</td>\n        </tr>\n    "},
b),data:b}))||0===h)c+=h;c+="\n        <tr>\n            <td><strong>"+p((d=e.l10n||a&&a.l10n,s={hash:{},data:b},d?d.call(a,"Name:",s):f.call(a,"l10n","Name:",s)))+'</strong></td>\n            <td><input type="text" name="name" size="50" value="';(d=e.name)?h=d.call(a,{hash:{},data:b}):(d=a&&a.name,h=typeof d===r?d.call(a,{hash:{},data:b}):d);c+=p(h)+'" class="username" ';if((h=e.unless.call(a,a&&a.canChangeName,{hash:{},inverse:q.noop,fn:q.program(17,function(a,d){return'disabled="disabled"'},b),
data:b}))||0===h)c+=h;c+="/></td>\n        </tr>\n    ";if((h=e["if"].call(a,a&&a.showEmail,{hash:{},inverse:q.noop,fn:q.program(19,function(a,d){var b,c,g;b=""+("\n        <tr>\n            <td><strong>"+p((c=e.l10n||a&&a.l10n,g={hash:{},data:d},c?c.call(a,"Email:",g):f.call(a,"l10n","Email:",g)))+'</strong></td>\n            <td><input type="text" name="email" size="50" value="');(c=e.email)?c=c.call(a,{hash:{},data:d}):(c=a&&a.email,c=typeof c===r?c.call(a,{hash:{},data:d}):c);return b+=p(c)+'" class="username"/></td>\n        </tr>\n    '},
b),data:b}))||0===h)c+=h;c+="\n    ";if((h=e["if"].call(a,a&&a.showMessage,{hash:{},inverse:q.noop,fn:q.program(21,function(a,c){var d,b,g;d=""+("\n        <tr>\n            <td><strong>"+p((b=e.l10n||a&&a.l10n,g={hash:{},data:c},b?b.call(a,"Initial Question:",g):f.call(a,"l10n","Initial Question:",g)))+'</strong></td>\n            <td valign="top"><textarea name="message" tabindex="0" cols="45" rows="2">');(b=e.message)?b=b.call(a,{hash:{},data:c}):(b=a&&a.message,b=typeof b===r?b.call(a,{hash:{},
data:c}):b);return d+=p(b)+"</textarea></td>\n        </tr>\n    "},b),data:b}))||0===h)c+=h;return c+='\n    </table>\n    <a href="javascript:void(0);" class="but" id="submit-survey">'+p((d=e.l10n||a&&a.l10n,s={hash:{},data:b},d?d.call(a,"Start Chat",s):f.call(a,"l10n","Start Chat",s)))+'</a>\n    <div class="clear">&nbsp;</div>\n</form>\n<div id="ajax-loader"><img src="'+p((h=(h=a&&a.page,null==h||!1===h?h:h.tplRoot),typeof h===r?h.apply(a):h))+'/images/ajax-loader.gif" alt="Loading..." /></div>'});
v["survey/layout"]=u(function(c,a,e,d,b){this.compilerInfo=[4,">= 1.0.0"];e=this.merge(e,c.helpers);d=this.merge(d,c.partials);b=b||{};var g,k,l=e.helperMissing,t=this.escapeExpression;c="\n";if((d=this.invokePartial(d._logo,"_logo",a,e,d,b))||0===d)c+=d;return c+='\n\n\n<div id="headers">\n    <div class="wndb"><div class="wndl"><div class="wndr"><div class="wndt"><div class="wndtl"><div class="wndtr"><div class="wndbl"><div class="wndbr">\n        <div class="buttons">\n            <a href="javascript:window.close();" title="'+
t((g=e.l10n||a&&a.l10n,k={hash:{},data:b},g?g.call(a,"Close",k):l.call(a,"l10n","Close",k)))+'"><img class="tpl-image iclosewin" src="'+t((d=(d=a&&a.page,null==d||!1===d?d:d.tplRoot),"function"===typeof d?d.apply(a):d))+'/images/free.gif" alt="'+t((g=e.l10n||a&&a.l10n,k={hash:{},data:b},g?g.call(a,"Close",k):l.call(a,"l10n","Close",k)))+'" /></a>\n        </div>\n        <div class="messagetxt">'+t((g=e.l10n||a&&a.l10n,k={hash:{},data:b},g?g.call(a,"Thank you for contacting us. Please fill out the form below and click the Start Chat button.",
k):l.call(a,"l10n","Thank you for contacting us. Please fill out the form below and click the Start Chat button.",k)))+'</div>\n    </div></div></div></div></div></div></div></div>\n</div>\n\n\n<div id="content-wrapper"></div>'})})();
