/*
 Copyright 2005-2014 the original author or authors.
 Licensed under the Apache License, Version 2.0 (the "License").
 You may obtain a copy of the License at
      http://www.apache.org/licenses/LICENSE-2.0
*/
(function(){var r=Handlebars.template,q=Handlebars.templates=Handlebars.templates||{};q._logo=r(function(b,c,e,a,d){function f(e){var a;return e=""+("\n                <a onclick=\"window.open('"+g((a=(a=e.page,null==a||!1===a?a:a.mibewHost),typeof a===h?a.apply(e):a))+'\');return false;" href="'+g((a=(a=e.page,null==a||!1===a?a:a.mibewHost),typeof a===h?a.apply(e):a))+'">\n                    <img src="'+g((a=(a=(a=e.page,null==a||!1===a?a:a.company),null==a||!1===a?a:a.chatLogoURL),typeof a===h?
a.apply(e):a))+'" alt=""/>\n                </a>\n            ')}function k(a){var e;return a=""+('\n                <img src="'+g((e=(e=(e=a.page,null==e||!1===e?e:e.company),null==e||!1===e?e:e.chatLogoURL),typeof e===h?e.apply(a):e))+'" alt=""/>\n            ')}function j(a){var e;return a=""+("\n                <a onclick=\"window.open('"+g((e=(e=a.page,null==e||!1===e?e:e.mibewHost),typeof e===h?e.apply(a):e))+'\');return false;" href="'+g((e=(e=a.page,null==e||!1===e?e:e.mibewHost),typeof e===
h?e.apply(a):e))+'">\n                    <img src="'+g((e=(e=a.page,null==e||!1===e?e:e.tplRoot),typeof e===h?e.apply(a):e))+'/images/default-logo.gif" alt=""/>\n                </a>\n            ')}function s(e){var a;return e=""+('\n                <img src="'+g((a=(a=e.page,null==a||!1===a?a:a.tplRoot),typeof a===h?a.apply(e):a))+'/images/default-logo.gif" alt=""/>\n            ')}this.compilerInfo=[4,">= 1.0.0"];e=this.merge(e,b.helpers);d=d||{};var m,h="function",g=this.escapeExpression,l=this;
b='\n<div id="top2">\n    <div id="logo">\n        ';if((d=e["if"].call(c,(m=(m=c.page,null==m||!1===m?m:m.company),null==m||!1===m?m:m.chatLogoURL),{hash:{},inverse:l.program(6,function(a,b){var c,d,f;c="\n            ";if((f=e["if"].call(a,(d=a.page,null==d||!1===d?d:d.mibewHost),{hash:{},inverse:l.program(9,s,b),fn:l.program(7,j,b),data:b}))||0===f)c+=f;return c+"\n        "},d),fn:l.program(1,function(a,b){var c,d,g;c="\n            ";if((g=e["if"].call(a,(d=a.page,null==d||!1===d?d:d.mibewHost),
{hash:{},inverse:l.program(4,k,b),fn:l.program(2,f,b),data:b}))||0===g)c+=g;return c+"\n        "},d),data:d}))||0===d)b+=d;return b+='\n        &nbsp;\n        <div id="page-title">'+g((m=(m=c.page,null==m||!1===m?m:m.title),typeof m===h?m.apply(c):m))+'</div>\n        <div class="clear">&nbsp;</div>\n    </div>\n</div>'});q.chat_avatar=r(function(b,c,e,a,d){this.compilerInfo=[4,">= 1.0.0"];e=this.merge(e,b.helpers);d=d||{};var f=this.escapeExpression;return(b=e["if"].call(c,c.imageLink,{hash:{},
inverse:this.program(3,function(){return'<div class="default-avatar"></div>'},d),fn:this.program(1,function(a,b){var c,d;c='<img src="';(d=e.imageLink)?d=d.call(a,{hash:{},data:b}):(d=a.imageLink,d="function"===typeof d?d.apply(a):d);return c+=f(d)+'" border="0" alt="" />'},d),data:d}))||0===b?b:""});q.chat_controls_close=r(function(b,c,e,a,d){this.compilerInfo=[4,">= 1.0.0"];e=this.merge(e,b.helpers);d=d||{};var f;b=e.helperMissing;a=this.escapeExpression;d={hash:{},data:d};return c='<div class="tpl-image" title="'+
(a((f=e.l10n||c.l10n,f?f.call(c,"chat.window.close_title",d):b.call(c,"l10n","chat.window.close_title",d)))+'"></div>')});q.chat_controls_history=r(function(b,c,e,a,d){this.compilerInfo=[4,">= 1.0.0"];e=this.merge(e,b.helpers);d=d||{};var f;b=e.helperMissing;a=this.escapeExpression;d={hash:{},data:d};return c='<div class="tpl-image" title="'+(a((f=e.l10n||c.l10n,f?f.call(c,"page.analysis.userhistory.title",d):b.call(c,"l10n","page.analysis.userhistory.title",d)))+'"></div>')});q.chat_controls_redirect=
r(function(b,c,e,a,d){this.compilerInfo=[4,">= 1.0.0"];e=this.merge(e,b.helpers);d=d||{};var f,k=e.helperMissing,j=this.escapeExpression;return(b=e["if"].call(c,(f=c.user,null==f||!1===f?f:f.canPost),{hash:{},inverse:this.noop,fn:this.program(1,function(a,b){var c,d;c={hash:{},data:b};return c='\n<div class="tpl-image" title="'+(j((d=e.l10n||a.l10n,d?d.call(a,"chat.window.toolbar.redirect_user",c):k.call(a,"l10n","chat.window.toolbar.redirect_user",c)))+'"></div>\n')},d),data:d}))||0===b?b:""});q.chat_controls_refresh=
r(function(b,c,e,a,d){this.compilerInfo=[4,">= 1.0.0"];e=this.merge(e,b.helpers);d=d||{};var f;b=e.helperMissing;a=this.escapeExpression;d={hash:{},data:d};return c='<div class="tpl-image" title="'+(a((f=e.l10n||c.l10n,f?f.call(c,"chat.window.toolbar.refresh",d):b.call(c,"l10n","chat.window.toolbar.refresh",d)))+'"></div>')});q.chat_controls_secure_mode=r(function(b,c,e){this.compilerInfo=[4,">= 1.0.0"];this.merge(e,b.helpers);return'<div class="tpl-image" title="SSL"></div>'});q.chat_controls_send_mail=
r(function(b,c,e,a,d){this.compilerInfo=[4,">= 1.0.0"];e=this.merge(e,b.helpers);d=d||{};var f;b=e.helperMissing;a=this.escapeExpression;d={hash:{},data:d};return c='<div class="tpl-image" title="'+(a((f=e.l10n||c.l10n,f?f.call(c,"chat.window.toolbar.mail_history",d):b.call(c,"l10n","chat.window.toolbar.mail_history",d)))+'"></div>')});q.chat_controls_sound=r(function(b,c,e,a,d){this.compilerInfo=[4,">= 1.0.0"];e=this.merge(e,b.helpers);d=d||{};var f=e.helperMissing,k=this.escapeExpression;return(b=
e["if"].call(c,c.enabled,{hash:{},inverse:this.program(3,function(a,b){var c,d;c={hash:{},data:b};return c='\n    <div class="tpl-image sound-control-off" title="'+(k((d=e.l10n||a.l10n,d?d.call(a,"chat.window.toolbar.turn_on_sound",c):f.call(a,"l10n","chat.window.toolbar.turn_on_sound",c)))+'"></div>\n')},d),fn:this.program(1,function(a,b){var c,d;c={hash:{},data:b};return c='\n    <div class="tpl-image sound-control-on" title="'+(k((d=e.l10n||a.l10n,d?d.call(a,"chat.window.toolbar.turn_off_sound",
c):f.call(a,"l10n","chat.window.toolbar.turn_off_sound",c)))+'"></div>\n')},d),data:d}))||0===b?b:""});q.chat_controls_user_name=r(function(b,c,e,a,d){function f(a,b){var c,d,f;c=""+('\n        <div class="user-name-control-input-bg"><input id="user-name-control-input" type="text" size="12" value="'+m((d=(d=a.user,null==d||!1===d?d:d.name),typeof d===s?d.apply(a):d))+'" class="username" /></div>\n        <a href="javascript:void(0)" class="user-name-control-set tpl-image" title="');f={hash:{},data:b};
return c+=m((d=e.l10n||a.l10n,d?d.call(a,"chat.client.changename",f):h.call(a,"l10n","chat.client.changename",f)))+'"></a>\n    '}function k(a,c){var b,d,f;f={hash:{},data:c};b='\n        <a href="javascript:void(0)" title="'+(m((d=e.l10n||a.l10n,d?d.call(a,"chat.client.changename",f):h.call(a,"l10n","chat.client.changename",f)))+'">'+m((d=(d=a.user,null==d||!1===d?d:d.name),typeof d===s?d.apply(a):d))+'</a>\n        <a class="user-name-control-change tpl-image" title="');f={hash:{},data:c};return b+=
m((d=e.l10n||a.l10n,d?d.call(a,"chat.client.changename",f):h.call(a,"l10n","chat.client.changename",f)))+'"></a>\n    '}this.compilerInfo=[4,">= 1.0.0"];e=this.merge(e,b.helpers);d=d||{};var j,s="function",m=this.escapeExpression,h=e.helperMissing,g=this;return(b=e["if"].call(c,(j=c.user,null==j||!1===j?j:j.canChangeName),{hash:{},inverse:g.program(6,function(a,b){var c,d;c={hash:{},data:b};return c="\n"+(m((d=e.l10n||a.l10n,d?d.call(a,"chat.client.name",c):h.call(a,"l10n","chat.client.name",c)))+
"&nbsp;"+m((d=(d=a.user,null==d||!1===d?d:d.name),typeof d===s?d.apply(a):d))+"\n")},d),fn:g.program(1,function(a,d){var c,b;c={hash:{},data:d};c='\n    <span class="user-name-control-prefix">'+(m((b=e.l10n||a.l10n,b?b.call(a,"chat.client.name",c):h.call(a,"l10n","chat.client.name",c)))+"</span>\n    ");if((b=e["if"].call(a,a.nameInput,{hash:{},inverse:g.program(4,k,d),fn:g.program(2,f,d),data:d}))||0===b)c+=b;return c+="\n"},d),data:d}))||0===b?b:""});q.chat_layout=r(function(b,c,e,a,d){this.compilerInfo=
[4,">= 1.0.0"];e=this.merge(e,b.helpers);a=this.merge(a,b.partials);d=d||{};var f,k=e.helperMissing,j=this.escapeExpression;b="\n";if((a=this.invokePartial(a._logo,"_logo",c,e,a,d))||0===a)b+=a;b+='\n\n\n<div id="chat-header">\n    <div class="bgc"><div class="bgl"><div class="bgr">\n        \n        <div id="controls-region"></div>\n    </div></div></div>\n</div>\n\n\n<div id="chat">\n    <div class="bgl"><div class="bgr"><div class="sdwbgc"><div class="sdwbgl"><div class="sdwbgr">\n        ';if((f=
e.unless.call(c,(a=c.user,null==a||!1===a?a:a.isAgent),{hash:{},inverse:this.noop,fn:this.program(1,function(){return'\n        <div id="avatar-region"></div>\n        '},d),data:d}))||0===f)b+=f;d={hash:{},data:d};return b=b+'\n        \n        <div id="messages-region"></div>\n        \n        <div id="status-region"></div>\n    </div></div></div></div></div>\n</div>\n\n\n<div id="message-form-region"></div>\n\n\n<div id="footer">'+(j((a=e.l10n||c.l10n,a?a.call(c,"chat.window.poweredby",d):k.call(c,
"l10n","chat.window.poweredby",d)))+' <a id="poweredByLink" href="http://mibew.org" title="Mibew Community" target="_blank">mibew.org</a></div>')});q.chat_message=r(function(b,c,e,a,d){this.compilerInfo=[4,">= 1.0.0"];e=this.merge(e,b.helpers);d=d||{};var f,k=this.escapeExpression,j=e.helperMissing;b={hash:{},data:d};b="<span>"+(k((f=e.formatTime||c.formatTime,f?f.call(c,c.created,b):j.call(c,"formatTime",c.created,b)))+"</span> \n");if((f=e["if"].call(c,c.name,{hash:{},inverse:this.noop,fn:this.program(1,
function(a,d){var c,b;c="<span class='n";(b=e.kindName)?b=b.call(a,{hash:{},data:d}):(b=a.kindName,b="function"===typeof b?b.apply(a):b);c+=k(b)+"'>";(b=e.name)?b=b.call(a,{hash:{},data:d}):(b=a.name,b="function"===typeof b?b.apply(a):b);return c+=k(b)+"</span>: "},d),data:d}))||0===f)b+=f;b+="\n<span class='m";(f=e.kindName)?f=f.call(c,{hash:{},data:d}):(f=c.kindName,f="function"===typeof f?f.apply(c):f);b+=k(f)+"'>";if((f=e["if"].call(c,c.allowFormatting,{hash:{},inverse:this.program(5,function(a,
b){var c,d;d={hash:{},data:b};return k((c=e.apply||a.apply,c?c.call(a,a.message,"urlReplace, nl2br",d):j.call(a,"apply",a.message,"urlReplace, nl2br",d)))},d),fn:this.program(3,function(a,b){var c,d;d={hash:{},data:b};return k((c=e.apply||a.apply,c?c.call(a,a.message,"urlReplace, nl2br, allowTags",d):j.call(a,"apply",a.message,"urlReplace, nl2br, allowTags",d)))},d),data:d}))||0===f)b+=f;return b+="</span><br/>"});q.chat_message_form=r(function(b,c,e,a,d){function f(a,b){var c,d;c={hash:{},data:b};
c='\n                <select id="predefined" size="1" class="answer">\n                    <option>'+(m((d=e.l10n||a.l10n,d?d.call(a,"chat.window.predefined.select_answer",c):h.call(a,"l10n","chat.window.predefined.select_answer",c)))+"</option>\n                ");if((d=e.each.call(a,a.predefinedAnswers,{hash:{},inverse:g.noop,fn:g.program(5,k,b),data:b}))||0===d)c+=d;return c+="\n                </select>\n            "}function k(a){var e;return a=""+("\n                    <option>"+m((e=a["short"],
typeof e===s?e.apply(a):e))+"</option>\n                ")}this.compilerInfo=[4,">= 1.0.0"];e=this.merge(e,b.helpers);d=d||{};var j,s="function",m=this.escapeExpression,h=e.helperMissing,g=this;b='<div id="message">\n';if((a=e["if"].call(c,(j=c.user,null==j||!1===j?j:j.canPost),{hash:{},inverse:g.noop,fn:g.program(1,function(){return'\n    <div class="bgc"><div class="bgl"><div class="bgr">\n        <textarea id="message-input" class="message" tabindex="0" rows="4" cols="10"></textarea>\n    </div></div></div>\n'},
d),data:d}))||0===a)b+=a;b+='\n</div>\n\n<div id="send">\n';if((a=e["if"].call(c,(j=c.user,null==j||!1===j?j:j.canPost),{hash:{},inverse:g.noop,fn:g.program(3,function(a,c){var b,d,t;b='\n    <div id="postmessage">\n        <div id="predefined-wrapper">\n            ';if((t=e["if"].call(a,(d=a.user,null==d||!1===d?d:d.isAgent),{hash:{},inverse:g.noop,fn:g.program(4,f,c),data:c}))||0===t)b+=t;t={hash:{},data:c};b=b+'\n        </div>\n        <a href="javascript:void(0)" id="send-message" title="'+
(m((d=e.l10n||a.l10n,d?d.call(a,"chat.window.send_message",t):h.call(a,"l10n","chat.window.send_message",t)))+'">');t={hash:{},data:c};return b+=m((d=e.l10n||a.l10n,d?d.call(a,"chat.window.send_message_short_and_shortcut",t):h.call(a,"l10n","chat.window.send_message_short_and_shortcut",t)))+"</a>\n    </div>\n"},d),data:d}))||0===a)b+=a;return b+'\n</div>\n<div class="clear"></div>'});q.chat_status_base=r(function(b,c,e,a,d){this.compilerInfo=[4,">= 1.0.0"];e=this.merge(e,b.helpers);d=d||{};b=this.escapeExpression;
(e=e.title)?e=e.call(c,{hash:{},data:d}):(e=c.title,e="function"===typeof e?e.apply(c):e);return b(e)});q.chat_status_message=r(function(b,c,e,a,d){this.compilerInfo=[4,">= 1.0.0"];e=this.merge(e,b.helpers);d=d||{};b=this.escapeExpression;(e=e.message)?e=e.call(c,{hash:{},data:d}):(e=c.message,e="function"===typeof e?e.apply(c):e);return b(e)});q.chat_status_typing=r(function(b,c,e,a,d){this.compilerInfo=[4,">= 1.0.0"];e=this.merge(e,b.helpers);d=d||{};var f;b=e.helperMissing;a=this.escapeExpression;
d={hash:{},data:d};return a((f=e.l10n||c.l10n,f?f.call(c,"typing.remote",d):b.call(c,"l10n","typing.remote",d)))});q.default_control=r(function(b,c,e,a,d){this.compilerInfo=[4,">= 1.0.0"];e=this.merge(e,b.helpers);d=d||{};a=this.escapeExpression;b="<strong>";(e=e.title)?e=e.call(c,{hash:{},data:d}):(e=c.title,e="function"===typeof e?e.apply(c):e);return b+=a(e)+"</strong>"});q.invitation_layout=r(function(b,c,e){this.compilerInfo=[4,">= 1.0.0"];this.merge(e,b.helpers);return'<div id="invitation-messages-region"></div>'});
q.leave_message_description=r(function(b,c,e,a,d){this.compilerInfo=[4,">= 1.0.0"];e=this.merge(e,b.helpers);d=d||{};var f,k=e.helperMissing,j=this.escapeExpression;a={hash:{},data:d};b='<div class="buttons">\n    <a href="javascript:window.close();" title="'+(j((f=e.l10n||c.l10n,f?f.call(c,"leavemessage.close",a):k.call(c,"l10n","leavemessage.close",a)))+'">\n        <img class="tpl-image iclosewin" src="'+j((f=(f=c.page,null==f||!1===f?f:f.tplRoot),"function"===typeof f?f.apply(c):f))+'/images/free.gif" alt="');
a={hash:{},data:d};b+=j((f=e.l10n||c.l10n,f?f.call(c,"leavemessage.close",a):k.call(c,"l10n","leavemessage.close",a)))+'" />\n    </a>\n</div>\n<div class="messagetxt">';a={hash:{},data:d};return b+=j((f=e.l10n||c.l10n,f?f.call(c,"leavemessage.descr",a):k.call(c,"l10n","leavemessage.descr",a)))+"</div>"});q.leave_message_form=r(function(b,c,e,a,d){function f(a,d){var b,c;b='<input type="hidden" name="group" value="';(c=e.groupId)?c=c.call(a,{hash:{},data:d}):(c=a.groupId,c=typeof c===g?c.apply(a):
c);return b+=l(c)+'"/>'}function k(a,c){var d,b,f;d=""+('\n                        <option value="'+l((b=a.id,typeof b===g?b.apply(a):b))+'" ');if((f=e["if"].call(a,a.selected,{hash:{},inverse:n.noop,fn:n.program(6,j,c),data:c}))||0===f)d+=f;return d+=">"+l((b=a.name,typeof b===g?b.apply(a):b))+"</option>\n                    "}function j(){return'selected="selected"'}function s(a,b){var c;return(c=e["if"].call(a,a.selected,{hash:{},inverse:n.noop,fn:n.program(9,m,b),data:b}))||0===c?c:""}function m(a){var b;
return l((b=a.description,typeof b===g?b.apply(a):b))}this.compilerInfo=[4,">= 1.0.0"];e=this.merge(e,b.helpers);d=d||{};var h,g="function",l=this.escapeExpression,n=this,p=e.helperMissing;b=""+('<form name="leaveMessageForm" method="post" action="">\n    <input type="hidden" name="style" value="'+l((h=(h=c.page,null==h||!1===h?h:h.style),typeof h===g?h.apply(c):h))+'"/>\n    <input type="hidden" name="info" value="');(a=e.info)?a=a.call(c,{hash:{},data:d}):(a=c.info,a=typeof a===g?a.apply(c):a);
b+=l(a)+'"/>\n    <input type="hidden" name="referrer" value="';(a=e.referrer)?a=a.call(c,{hash:{},data:d}):(a=c.referrer,a=typeof a===g?a.apply(c):a);b+=l(a)+'"/>\n    ';if((a=e.unless.call(c,c.groups,{hash:{},inverse:n.noop,fn:n.program(1,function(a,b){var c;return(c=e["if"].call(a,a.groupId,{hash:{},inverse:n.noop,fn:n.program(2,f,b),data:b}))||0===c?c:""},d),data:d}))||0===a)b+=a;a={hash:{},data:d};b=b+'\n\n    <div class="errors"></div>\n\n    <table cellspacing="1" cellpadding="5" border="0" class="form">\n        <tr>\n            <td><strong>'+
(l((h=e.l10n||c.l10n,h?h.call(c,"form.field.email",a):p.call(c,"l10n","form.field.email",a)))+':</strong></td>\n            <td><input type="text" name="email" size="50" value="');(a=e.email)?a=a.call(c,{hash:{},data:d}):(a=c.email,a=typeof a===g?a.apply(c):a);b+=l(a)+'" class="username"/></td>\n        </tr>\n        <tr>\n            <td><strong>';a={hash:{},data:d};b+=l((h=e.l10n||c.l10n,h?h.call(c,"form.field.name",a):p.call(c,"l10n","form.field.name",a)))+':</strong></td>\n            <td><input type="text" name="name" size="50" value="';
(a=e.name)?a=a.call(c,{hash:{},data:d}):(a=c.name,a=typeof a===g?a.apply(c):a);b+=l(a)+'" class="username"/></td>\n        </tr>\n    ';if((a=e["if"].call(c,c.groups,{hash:{},inverse:n.noop,fn:n.program(4,function(a,b){var c,d,f;f={hash:{},data:b};c='\n        <tr>\n            <td class="text"><strong>'+(l((d=e.l10n||a.l10n,d?d.call(a,"form.field.department",f):p.call(a,"l10n","form.field.department",f)))+'</strong></td>\n            <td>\n                <select name="group" style="min-width:200px;">\n                    ');
if((f=e.each.call(a,a.groups,{hash:{},inverse:n.noop,fn:n.program(5,k,b),data:b}))||0===f)c+=f;c+='\n                </select>\n            </td>\n        </tr>\n        <tr>\n            <td class="text"><strong>';f={hash:{},data:b};c+=l((d=e.l10n||a.l10n,d?d.call(a,"form.field.department.description",f):p.call(a,"l10n","form.field.department.description",f)))+'</strong></td>\n            <td class="text" id="groupDescription">\n                ';if((f=e.each.call(a,a.groups,{hash:{},inverse:n.noop,
fn:n.program(8,s,b),data:b}))||0===f)c+=f;return c+="\n            </td>\n        </tr>\n    "},d),data:d}))||0===a)b+=a;b+="\n        <tr>\n            <td><strong>";a={hash:{},data:d};b+=l((h=e.l10n||c.l10n,h?h.call(c,"form.field.message",a):p.call(c,"l10n","form.field.message",a)))+':</strong></td>\n            <td valign="top">\n                <textarea name="message" tabindex="0" cols="40" rows="5">';(a=e.message)?a=a.call(c,{hash:{},data:d}):(a=c.message,a=typeof a===g?a.apply(c):a);b+=l(a)+
"</textarea>\n            </td>\n        </tr>\n    ";if((a=e["if"].call(c,c.showCaptcha,{hash:{},inverse:n.noop,fn:n.program(11,function(){return'\n        <tr>\n            <td><img id="captcha-img" src="captcha.php"/></td>\n            <td><input type="text" name="captcha" size="50" maxlength="15" value="" class="username"/></td>\n        </tr>\n    '},d),data:d}))||0===a)b+=a;b+='\n    </table>\n    <a href="javascript:void(0);" class="but" id="send-message">';a={hash:{},data:d};return b+=l((h=
e.l10n||c.l10n,h?h.call(c,"mailthread.perform",a):p.call(c,"l10n","mailthread.perform",a)))+'</a>\n    <div class="clear">&nbsp;</div>\n</form>\n<div id="ajax-loader"><img src="'+l((h=(h=c.page,null==h||!1===h?h:h.tplRoot),typeof h===g?h.apply(c):h))+'/images/ajax-loader.gif" alt="Loading..." /></div>'});q.leave_message_layout=r(function(b,c,e,a,d){this.compilerInfo=[4,">= 1.0.0"];e=this.merge(e,b.helpers);a=this.merge(a,b.partials);d=d||{};b="\n";if((c=this.invokePartial(a._logo,"_logo",c,e,a,d))||
0===c)b+=c;return b+'\n\n\n<div id="headers">\n    <div class="wndb"><div class="wndl"><div class="wndr"><div class="wndt"><div class="wndtl"><div class="wndtr"><div class="wndbl"><div class="wndbr" id="description-region">\n    </div></div></div></div></div></div></div></div>\n</div>\n\n\n<div id="content-wrapper"></div>'});q.leave_message_sent_description=r(function(b,c,e,a,d){this.compilerInfo=[4,">= 1.0.0"];e=this.merge(e,b.helpers);d=d||{};var f,k=e.helperMissing,j=this.escapeExpression;a={hash:{},
data:d};b='<div class="buttons">\n        <a href="javascript:window.close();" title="'+(j((f=e.l10n||c.l10n,f?f.call(c,"chat.mailthread.sent.close",a):k.call(c,"l10n","chat.mailthread.sent.close",a)))+'">\n            <img class="tpl-image iclosewin" src="'+j((f=(f=c.page,null==f||!1===f?f:f.tplRoot),"function"===typeof f?f.apply(c):f))+'/images/free.gif" alt="');a={hash:{},data:d};b+=j((f=e.l10n||c.l10n,f?f.call(c,"chat.mailthread.sent.close",a):k.call(c,"l10n","chat.mailthread.sent.close",a)))+
'" />\n        </a>\n</div>\n<div class="messagetxt">';a={hash:{},data:d};return b+=j((f=e.l10n||c.l10n,f?f.call(c,"leavemessage.sent.message",a):k.call(c,"l10n","leavemessage.sent.message",a)))+"</div>"});q.message=r(function(b,c,e,a,d){this.compilerInfo=[4,">= 1.0.0"];e=this.merge(e,b.helpers);d=d||{};var f,k=this.escapeExpression,j=e.helperMissing;b={hash:{},data:d};b="<span>"+(k((f=e.formatTime||c.formatTime,f?f.call(c,c.created,b):j.call(c,"formatTime",c.created,b)))+"</span>\n");if((f=e["if"].call(c,
c.name,{hash:{},inverse:this.noop,fn:this.program(1,function(a,b){var c,d;c="<span class='n";(d=e.kindName)?d=d.call(a,{hash:{},data:b}):(d=a.kindName,d="function"===typeof d?d.apply(a):d);c+=k(d)+"'>";(d=e.name)?d=d.call(a,{hash:{},data:b}):(d=a.name,d="function"===typeof d?d.apply(a):d);return c+=k(d)+"</span>: "},d),data:d}))||0===f)b+=f;b+="\n<span class='m";(f=e.kindName)?f=f.call(c,{hash:{},data:d}):(f=c.kindName,f="function"===typeof f?f.apply(c):f);b+=k(f)+"'>";if((f=e["if"].call(c,c.allowFormatting,
{hash:{},inverse:this.program(5,function(a,c){var d,b;b={hash:{},data:c};return k((d=e.apply||a.apply,d?d.call(a,a.message,"urlReplace, nl2br",b):j.call(a,"apply",a.message,"urlReplace, nl2br",b)))},d),fn:this.program(3,function(a,d){var c,b;b={hash:{},data:d};return k((c=e.apply||a.apply,c?c.call(a,a.message,"urlReplace, nl2br, allowTags",b):j.call(a,"apply",a.message,"urlReplace, nl2br, allowTags",b)))},d),data:d}))||0===f)b+=f;return b+="</span><br/>"});q.survey_form=r(function(b,c,e,a,d){function f(a,
c){var d,b;d='<input type="hidden" name="group" value="';(b=e.groupId)?b=b.call(a,{hash:{},data:c}):(b=a.groupId,b=typeof b===l?b.apply(a):b);return d+=n(b)+'"/>'}function k(a,b){var d,c,f;d=""+('\n                        <option value="'+n((c=a.id,typeof c===l?c.apply(a):c))+'" ');if((f=e["if"].call(a,a.selected,{hash:{},inverse:p.noop,fn:p.program(10,j,b),data:b}))||0===f)d+=f;d+=">"+n((c=a.name,typeof c===l?c.apply(a):c));if((f=e.unless.call(a,a.online,{hash:{},inverse:p.noop,fn:p.program(12,r,
b),data:b}))||0===f)d+=f;return d+"</option>\n                    "}function j(){return'selected="selected"'}function r(){return" (offline)"}function m(a,b){var d;return(d=e["if"].call(a,a.selected,{hash:{},inverse:p.noop,fn:p.program(15,h,b),data:b}))||0===d?d:""}function h(a){var b;return n((b=a.description,typeof b===l?b.apply(a):b))}this.compilerInfo=[4,">= 1.0.0"];e=this.merge(e,b.helpers);d=d||{};var g,l="function",n=this.escapeExpression,p=this,q=e.helperMissing;b=""+('<form name="surveyForm" method="post" action="">\n    <input type="hidden" name="style" value="'+
n((g=(g=c.page,null==g||!1===g?g:g.style),typeof g===l?g.apply(c):g))+'"/>\n    <input type="hidden" name="info" value="');(a=e.info)?a=a.call(c,{hash:{},data:d}):(a=c.info,a=typeof a===l?a.apply(c):a);b+=n(a)+'"/>\n    <input type="hidden" name="referrer" value="';(a=e.referrer)?a=a.call(c,{hash:{},data:d}):(a=c.referrer,a=typeof a===l?a.apply(c):a);b+=n(a)+'"/>\n    <input type="hidden" name="survey" value="on"/>\n    ';if((a=e.unless.call(c,c.showEmail,{hash:{},inverse:p.noop,fn:p.program(1,function(a,
b){var d,c;d='<input type="hidden" name="email" value="';(c=e.email)?c=c.call(a,{hash:{},data:b}):(c=a.email,c=typeof c===l?c.apply(a):c);return d+=n(c)+'"/>'},d),data:d}))||0===a)b+=a;b+="\n    ";if((a=e.unless.call(c,c.groups,{hash:{},inverse:p.noop,fn:p.program(3,function(a,b){var c;return(c=e["if"].call(a,a.groupId,{hash:{},inverse:p.noop,fn:p.program(4,f,b),data:b}))||0===c?c:""},d),data:d}))||0===a)b+=a;b+="\n    ";if((a=e.unless.call(c,c.showMessage,{hash:{},inverse:p.noop,fn:p.program(6,function(a,
b){var c,d;c='<input type="hidden" name="message" value="';(d=e.message)?d=d.call(a,{hash:{},data:b}):(d=a.message,d=typeof d===l?d.apply(a):d);return c+=n(d)+'"/>'},d),data:d}))||0===a)b+=a;b+='\n\n    <div class="errors"></div>\n\n    <table class="form">\n    ';if((a=e["if"].call(c,c.groups,{hash:{},inverse:p.noop,fn:p.program(8,function(a,d){var b,c,f;f={hash:{},data:d};b="\n        <tr>\n            <td><strong>"+(n((c=e.l10n||a.l10n,c?c.call(a,"form.field.department",f):q.call(a,"l10n","form.field.department",
f)))+'</strong></td>\n            <td>\n                <select name="group">\n                    ');if((f=e.each.call(a,a.groups,{hash:{},inverse:p.noop,fn:p.program(9,k,d),data:d}))||0===f)b+=f;b+="\n                </select>\n            </td>\n        </tr>\n        <tr>\n            <td><strong>";f={hash:{},data:d};b+=n((c=e.l10n||a.l10n,c?c.call(a,"form.field.department.description",f):q.call(a,"l10n","form.field.department.description",f)))+'</strong></td>\n            <td id="groupDescription">';
if((f=e.each.call(a,a.groups,{hash:{},inverse:p.noop,fn:p.program(14,m,d),data:d}))||0===f)b+=f;return b+="</td>\n        </tr>\n    "},d),data:d}))||0===a)b+=a;a={hash:{},data:d};b=b+"\n        <tr>\n            <td><strong>"+(n((g=e.l10n||c.l10n,g?g.call(c,"presurvey.name",a):q.call(c,"l10n","presurvey.name",a)))+'</strong></td>\n            <td><input type="text" name="name" size="50" value="');(a=e.name)?a=a.call(c,{hash:{},data:d}):(a=c.name,a=typeof a===l?a.apply(c):a);b+=n(a)+'" class="username" ';
if((a=e.unless.call(c,c.canChangeName,{hash:{},inverse:p.noop,fn:p.program(17,function(){return'disabled="disabled"'},d),data:d}))||0===a)b+=a;b+="/></td>\n        </tr>\n    ";if((a=e["if"].call(c,c.showEmail,{hash:{},inverse:p.noop,fn:p.program(19,function(a,b){var d,c;d={hash:{},data:b};d="\n        <tr>\n            <td><strong>"+(n((c=e.l10n||a.l10n,c?c.call(a,"presurvey.mail",d):q.call(a,"l10n","presurvey.mail",d)))+'</strong></td>\n            <td><input type="text" name="email" size="50" value="');
(c=e.email)?c=c.call(a,{hash:{},data:b}):(c=a.email,c=typeof c===l?c.apply(a):c);return d+=n(c)+'" class="username"/></td>\n        </tr>\n    '},d),data:d}))||0===a)b+=a;b+="\n    ";if((a=e["if"].call(c,c.showMessage,{hash:{},inverse:p.noop,fn:p.program(21,function(a,c){var d,b;d={hash:{},data:c};d="\n        <tr>\n            <td><strong>"+(n((b=e.l10n||a.l10n,b?b.call(a,"presurvey.question",d):q.call(a,"l10n","presurvey.question",d)))+'</strong></td>\n            <td valign="top"><textarea name="message" tabindex="0" cols="45" rows="2">');
(b=e.message)?b=b.call(a,{hash:{},data:c}):(b=a.message,b=typeof b===l?b.apply(a):b);return d+=n(b)+"</textarea></td>\n        </tr>\n    "},d),data:d}))||0===a)b+=a;b+='\n    </table>\n    <a href="javascript:void(0);" class="but" id="submit-survey">';a={hash:{},data:d};return b+=n((g=e.l10n||c.l10n,g?g.call(c,"presurvey.submit",a):q.call(c,"l10n","presurvey.submit",a)))+'</a>\n    <div class="clear">&nbsp;</div>\n</form>\n<div id="ajax-loader"><img src="'+n((g=(g=c.page,null==g||!1===g?g:g.tplRoot),
typeof g===l?g.apply(c):g))+'/images/ajax-loader.gif" alt="Loading..." /></div>'});q.survey_layout=r(function(b,c,e,a,d){this.compilerInfo=[4,">= 1.0.0"];e=this.merge(e,b.helpers);a=this.merge(a,b.partials);d=d||{};var f,k=e.helperMissing,j=this.escapeExpression;b="\n";if((a=this.invokePartial(a._logo,"_logo",c,e,a,d))||0===a)b+=a;f={hash:{},data:d};b=b+'\n\n\n<div id="headers">\n    <div class="wndb"><div class="wndl"><div class="wndr"><div class="wndt"><div class="wndtl"><div class="wndtr"><div class="wndbl"><div class="wndbr">\n        <div class="buttons">\n            <a href="javascript:window.close();" title="'+
(j((a=e.l10n||c.l10n,a?a.call(c,"leavemessage.close",f):k.call(c,"l10n","leavemessage.close",f)))+'"><img class="tpl-image iclosewin" src="'+j((a=(a=c.page,null==a||!1===a?a:a.tplRoot),"function"===typeof a?a.apply(c):a))+'/images/free.gif" alt="');f={hash:{},data:d};b+=j((a=e.l10n||c.l10n,a?a.call(c,"leavemessage.close",f):k.call(c,"l10n","leavemessage.close",f)))+'" /></a>\n        </div>\n        <div class="messagetxt">';f={hash:{},data:d};return b+=j((a=e.l10n||c.l10n,a?a.call(c,"presurvey.intro",
f):k.call(c,"l10n","presurvey.intro",f)))+'</div>\n    </div></div></div></div></div></div></div></div>\n</div>\n\n\n<div id="content-wrapper"></div>'})})();
