/*
 Copyright 2005-2014 the original author or authors.
 Licensed under the Apache License, Version 2.0 (the "License").
 You may obtain a copy of the License at
      http://www.apache.org/licenses/LICENSE-2.0
*/
(function(){var k=Handlebars.template,l=Handlebars.templates=Handlebars.templates||{};l._logo=k({1:function(a,d,c,e){var b;c="\n            ";if((b=d["if"].call(a,(b=a&&a.page,null==b||!1===b?b:b.mibewHost),{name:"if",hash:{},fn:this.program(2,e),inverse:this.program(4,e),data:e}))||0===b)c+=b;return c+"\n        "},2:function(a,d,c,e){var b;d=this.escapeExpression;return"\n                <a onclick=\"window.open('"+d((b=(b=a&&a.page,null==b||!1===b?b:b.mibewHost),"function"===typeof b?b.apply(a):
b))+'\');return false;" href="'+d((b=(b=a&&a.page,null==b||!1===b?b:b.mibewHost),"function"===typeof b?b.apply(a):b))+'">\n                    <img src="'+d((b=(b=(b=a&&a.page,null==b||!1===b?b:b.company),null==b||!1===b?b:b.chatLogoURL),"function"===typeof b?b.apply(a):b))+'" alt=""/>\n                </a>\n            '},4:function(a,d,c,e){var b;d=this.escapeExpression;return'\n                <img src="'+d((b=(b=(b=a&&a.page,null==b||!1===b?b:b.company),null==b||!1===b?b:b.chatLogoURL),"function"===
typeof b?b.apply(a):b))+'" alt=""/>\n            '},6:function(a,d,c,e){var b;c="\n            ";if((b=d["if"].call(a,(b=a&&a.page,null==b||!1===b?b:b.mibewHost),{name:"if",hash:{},fn:this.program(7,e),inverse:this.program(9,e),data:e}))||0===b)c+=b;return c+"\n        "},7:function(a,d,c,e){var b;d=this.escapeExpression;return"\n                <a onclick=\"window.open('"+d((b=(b=a&&a.page,null==b||!1===b?b:b.mibewHost),"function"===typeof b?b.apply(a):b))+'\');return false;" href="'+d((b=(b=a&&
a.page,null==b||!1===b?b:b.mibewHost),"function"===typeof b?b.apply(a):b))+'">\n                    <img src="'+d((b=(b=a&&a.page,null==b||!1===b?b:b.tplRoot),"function"===typeof b?b.apply(a):b))+'/images/default-logo.gif" alt=""/>\n                </a>\n            '},9:function(a,d,c,e){var b;d=this.escapeExpression;return'\n                <img src="'+d((b=(b=a&&a.page,null==b||!1===b?b:b.tplRoot),"function"===typeof b?b.apply(a):b))+'/images/default-logo.gif" alt=""/>\n            '},compiler:[5,
">= 2.0.0"],main:function(a,d,c,e){var b;c=this.escapeExpression;var f='\n<div id="top2">\n    <div id="logo">\n        ';if((b=d["if"].call(a,(b=(b=a&&a.page,null==b||!1===b?b:b.company),null==b||!1===b?b:b.chatLogoURL),{name:"if",hash:{},fn:this.program(1,e),inverse:this.program(6,e),data:e}))||0===b)f+=b;return f+'\n        &nbsp;\n        <div id="page-title">'+c((b=(b=a&&a.page,null==b||!1===b?b:b.title),"function"===typeof b?b.apply(a):b))+'</div>\n        <div class="clear">&nbsp;</div>\n    </div>\n</div>'},
useData:!0});l.chat_avatar=k({1:function(a,d,c,e){var b;c=this.escapeExpression;return'<img src="'+c((b=d.imageLink||a&&a.imageLink,"function"===typeof b?b.call(a,{name:"imageLink",hash:{},data:e}):b))+'" border="0" alt="" />'},3:function(a,d,c,e){return'<div class="default-avatar"></div>'},compiler:[5,">= 2.0.0"],main:function(a,d,c,e){return(a=d["if"].call(a,a&&a.imageLink,{name:"if",hash:{},fn:this.program(1,e),inverse:this.program(3,e),data:e}))||0===a?a:""},useData:!0});l.chat_controls_close=
k({compiler:[5,">= 2.0.0"],main:function(a,d,c,e){var b;c=d.helperMissing;var f=this.escapeExpression;return'<div class="tpl-image" title="'+f((b=d.l10n||a&&a.l10n||c,b.call(a,"chat.window.close_title",{name:"l10n",hash:{},data:e})))+'"></div>'},useData:!0});l.chat_controls_history=k({compiler:[5,">= 2.0.0"],main:function(a,d,c,e){var b;c=d.helperMissing;var f=this.escapeExpression;return'<div class="tpl-image" title="'+f((b=d.l10n||a&&a.l10n||c,b.call(a,"page.analysis.userhistory.title",{name:"l10n",
hash:{},data:e})))+'"></div>'},useData:!0});l.chat_controls_redirect=k({1:function(a,d,c,e){var b;c=d.helperMissing;var f=this.escapeExpression;return'\n<div class="tpl-image" title="'+f((b=d.l10n||a&&a.l10n||c,b.call(a,"chat.window.toolbar.redirect_user",{name:"l10n",hash:{},data:e})))+'"></div>\n'},compiler:[5,">= 2.0.0"],main:function(a,d,c,e){var b;return(b=d["if"].call(a,(b=a&&a.user,null==b||!1===b?b:b.canPost),{name:"if",hash:{},fn:this.program(1,e),inverse:this.noop,data:e}))||0===b?b:""},
useData:!0});l.chat_controls_refresh=k({compiler:[5,">= 2.0.0"],main:function(a,d,c,e){var b;c=d.helperMissing;var f=this.escapeExpression;return'<div class="tpl-image" title="'+f((b=d.l10n||a&&a.l10n||c,b.call(a,"chat.window.toolbar.refresh",{name:"l10n",hash:{},data:e})))+'"></div>'},useData:!0});l.chat_controls_secure_mode=k({compiler:[5,">= 2.0.0"],main:function(a,d,c,e){return'<div class="tpl-image" title="SSL"></div>'},useData:!0});l.chat_controls_send_mail=k({compiler:[5,">= 2.0.0"],main:function(a,
d,c,e){var b;c=d.helperMissing;var f=this.escapeExpression;return'<div class="tpl-image" title="'+f((b=d.l10n||a&&a.l10n||c,b.call(a,"chat.window.toolbar.mail_history",{name:"l10n",hash:{},data:e})))+'"></div>'},useData:!0});l.chat_controls_sound=k({1:function(a,d,c,e){var b;c=d.helperMissing;var f=this.escapeExpression;return'\n    <div class="tpl-image sound-control-on" title="'+f((b=d.l10n||a&&a.l10n||c,b.call(a,"chat.window.toolbar.turn_off_sound",{name:"l10n",hash:{},data:e})))+'"></div>\n'},
3:function(a,d,c,e){var b;c=d.helperMissing;var f=this.escapeExpression;return'\n    <div class="tpl-image sound-control-off" title="'+f((b=d.l10n||a&&a.l10n||c,b.call(a,"chat.window.toolbar.turn_on_sound",{name:"l10n",hash:{},data:e})))+'"></div>\n'},compiler:[5,">= 2.0.0"],main:function(a,d,c,e){return(a=d["if"].call(a,a&&a.enabled,{name:"if",hash:{},fn:this.program(1,e),inverse:this.program(3,e),data:e}))||0===a?a:""},useData:!0});l.chat_controls_user_name=k({1:function(a,d,c,e){var b;c=d.helperMissing;
var f=this.escapeExpression;c='\n    <span class="user-name-control-prefix">'+f((b=d.l10n||a&&a.l10n||c,b.call(a,"chat.client.name",{name:"l10n",hash:{},data:e})))+"</span>\n    ";if((a=d["if"].call(a,a&&a.nameInput,{name:"if",hash:{},fn:this.program(2,e),inverse:this.program(4,e),data:e}))||0===a)c+=a;return c+"\n"},2:function(a,d,c,e){var b,f;c=this.escapeExpression;var h=d.helperMissing;return'\n        <div class="user-name-control-input-bg"><input id="user-name-control-input" type="text" size="12" value="'+
c((b=(b=a&&a.user,null==b||!1===b?b:b.name),"function"===typeof b?b.apply(a):b))+'" class="username" /></div>\n        <a href="javascript:void(0)" class="user-name-control-set tpl-image" title="'+c((f=d.l10n||a&&a.l10n||h,f.call(a,"chat.client.changename",{name:"l10n",hash:{},data:e})))+'"></a>\n    '},4:function(a,d,c,e){var b,f;c=d.helperMissing;var h=this.escapeExpression;return'\n        <a href="javascript:void(0)" title="'+h((f=d.l10n||a&&a.l10n||c,f.call(a,"chat.client.changename",{name:"l10n",
hash:{},data:e})))+'">'+h((b=(b=a&&a.user,null==b||!1===b?b:b.name),"function"===typeof b?b.apply(a):b))+'</a>\n        <a class="user-name-control-change tpl-image" title="'+h((f=d.l10n||a&&a.l10n||c,f.call(a,"chat.client.changename",{name:"l10n",hash:{},data:e})))+'"></a>\n    '},6:function(a,d,c,e){var b,f;c=d.helperMissing;var h=this.escapeExpression;return"\n"+h((f=d.l10n||a&&a.l10n||c,f.call(a,"chat.client.name",{name:"l10n",hash:{},data:e})))+"&nbsp;"+h((b=(b=a&&a.user,null==b||!1===b?b:b.name),
"function"===typeof b?b.apply(a):b))+"\n"},compiler:[5,">= 2.0.0"],main:function(a,d,c,e){var b;return(b=d["if"].call(a,(b=a&&a.user,null==b||!1===b?b:b.canChangeName),{name:"if",hash:{},fn:this.program(1,e),inverse:this.program(6,e),data:e}))||0===b?b:""},useData:!0});l.chat_layout=k({1:function(a,d,c,e){return'\n        <div id="avatar-region"></div>\n        '},compiler:[5,">= 2.0.0"],main:function(a,d,c,e){var b,f=d.helperMissing,h=this.escapeExpression,g="\n";if((c=this.invokePartial(c._logo,
"_logo",a,void 0,d,c,e))||0===c)g+=c;g+='\n\n\n<div id="chat-header">\n    <div class="bgc"><div class="bgl"><div class="bgr">\n        \n        <div id="controls-region"></div>\n    </div></div></div>\n</div>\n\n\n<div id="chat">\n    <div class="bgl"><div class="bgr"><div class="sdwbgc"><div class="sdwbgl"><div class="sdwbgr">\n        ';if((c=d.unless.call(a,(c=a&&a.user,null==c||!1===c?c:c.isAgent),{name:"unless",hash:{},fn:this.program(1,e),inverse:this.noop,data:e}))||0===c)g+=c;return g+'\n        \n        <div id="messages-region"></div>\n        \n        <div id="status-region"></div>\n    </div></div></div></div></div>\n</div>\n\n\n<div id="message-form-region"></div>\n\n\n<div id="footer">'+
h((b=d.l10n||a&&a.l10n||f,b.call(a,"chat.window.poweredby",{name:"l10n",hash:{},data:e})))+' <a id="poweredByLink" href="http://mibew.org" title="Mibew Community" target="_blank">mibew.org</a></div>'},usePartial:!0,useData:!0});l.chat_message=k({1:function(a,d,c,e){var b;c=this.escapeExpression;return"<span class='n"+c((b=d.kindName||a&&a.kindName,"function"===typeof b?b.call(a,{name:"kindName",hash:{},data:e}):b))+"'>"+c((b=d.name||a&&a.name,"function"===typeof b?b.call(a,{name:"name",hash:{},data:e}):
b))+"</span>: "},3:function(a,d,c,e){var b;c=d.helperMissing;var f=this.escapeExpression;return f((b=d.apply||a&&a.apply||c,b.call(a,a&&a.message,"urlReplace, nl2br, allowTags",{name:"apply",hash:{},data:e})))},5:function(a,d,c,e){var b;c=d.helperMissing;var f=this.escapeExpression;return f((b=d.apply||a&&a.apply||c,b.call(a,a&&a.message,"urlReplace, nl2br",{name:"apply",hash:{},data:e})))},compiler:[5,">= 2.0.0"],main:function(a,d,c,e){var b,f;b=d.helperMissing;c=this.escapeExpression;var h="<span>"+
c((f=d.formatTime||a&&a.formatTime||b,f.call(a,a&&a.created,{name:"formatTime",hash:{},data:e})))+"</span> \n";if((b=d["if"].call(a,a&&a.name,{name:"if",hash:{},fn:this.program(1,e),inverse:this.noop,data:e}))||0===b)h+=b;h+="\n<span class='m"+c((f=d.kindName||a&&a.kindName,"function"===typeof f?f.call(a,{name:"kindName",hash:{},data:e}):f))+"'>";if((b=d["if"].call(a,a&&a.allowFormatting,{name:"if",hash:{},fn:this.program(3,e),inverse:this.program(5,e),data:e}))||0===b)h+=b;return h+"</span><br/>"},
useData:!0});l.chat_message_form=k({1:function(a,d,c,e){return'\n    <div class="bgc"><div class="bgl"><div class="bgr">\n        <textarea id="message-input" class="message" tabindex="0" rows="4" cols="10"></textarea>\n    </div></div></div>\n'},3:function(a,d,c,e){var b,f;c=d.helperMissing;var h=this.escapeExpression,g='\n    <div id="postmessage">\n        <div id="predefined-wrapper">\n            ';if((b=d["if"].call(a,(b=a&&a.user,null==b||!1===b?b:b.isAgent),{name:"if",hash:{},fn:this.program(4,
e),inverse:this.noop,data:e}))||0===b)g+=b;return g+'\n        </div>\n        <a href="javascript:void(0)" id="send-message" title="'+h((f=d.l10n||a&&a.l10n||c,f.call(a,"chat.window.send_message",{name:"l10n",hash:{},data:e})))+'">'+h((f=d.l10n||a&&a.l10n||c,f.call(a,"chat.window.send_message_short_and_shortcut",{name:"l10n",hash:{},data:e})))+"</a>\n    </div>\n"},4:function(a,d,c,e){var b;c=d.helperMissing;var f=this.escapeExpression;c='\n                <select id="predefined" size="1" class="answer">\n                    <option>'+
f((b=d.l10n||a&&a.l10n||c,b.call(a,"chat.window.predefined.select_answer",{name:"l10n",hash:{},data:e})))+"</option>\n                ";if((a=d.each.call(a,a&&a.predefinedAnswers,{name:"each",hash:{},fn:this.program(5,e),inverse:this.noop,data:e}))||0===a)c+=a;return c+"\n                </select>\n            "},5:function(a,d,c,e){var b;d=this.escapeExpression;return"\n                    <option>"+d((b=a&&a["short"],"function"===typeof b?b.apply(a):b))+"</option>\n                "},compiler:[5,
">= 2.0.0"],main:function(a,d,c,e){var b;c='<div id="message">\n';if((b=d["if"].call(a,(b=a&&a.user,null==b||!1===b?b:b.canPost),{name:"if",hash:{},fn:this.program(1,e),inverse:this.noop,data:e}))||0===b)c+=b;c+='\n</div>\n\n<div id="send">\n';if((b=d["if"].call(a,(b=a&&a.user,null==b||!1===b?b:b.canPost),{name:"if",hash:{},fn:this.program(3,e),inverse:this.noop,data:e}))||0===b)c+=b;return c+'\n</div>\n<div class="clear"></div>'},useData:!0});l.chat_status_base=k({compiler:[5,">= 2.0.0"],main:function(a,
d,c,e){var b;c=this.escapeExpression;return c((b=d.title||a&&a.title,"function"===typeof b?b.call(a,{name:"title",hash:{},data:e}):b))},useData:!0});l.chat_status_message=k({compiler:[5,">= 2.0.0"],main:function(a,d,c,e){var b;c=this.escapeExpression;return c((b=d.message||a&&a.message,"function"===typeof b?b.call(a,{name:"message",hash:{},data:e}):b))},useData:!0});l.chat_status_typing=k({compiler:[5,">= 2.0.0"],main:function(a,d,c,e){var b;c=d.helperMissing;var f=this.escapeExpression;return f((b=
d.l10n||a&&a.l10n||c,b.call(a,"typing.remote",{name:"l10n",hash:{},data:e})))},useData:!0});l.default_control=k({compiler:[5,">= 2.0.0"],main:function(a,d,c,e){var b;c=this.escapeExpression;return"<strong>"+c((b=d.title||a&&a.title,"function"===typeof b?b.call(a,{name:"title",hash:{},data:e}):b))+"</strong>"},useData:!0});l.invitation_layout=k({compiler:[5,">= 2.0.0"],main:function(a,d,c,e){return'<div id="invitation-messages-region"></div>'},useData:!0});l.leave_message_description=k({compiler:[5,
">= 2.0.0"],main:function(a,d,c,e){var b,f;c=d.helperMissing;var h=this.escapeExpression;return'<div class="buttons">\n    <a href="javascript:window.close();" title="'+h((f=d.l10n||a&&a.l10n||c,f.call(a,"leavemessage.close",{name:"l10n",hash:{},data:e})))+'">\n        <img class="tpl-image iclosewin" src="'+h((b=(b=a&&a.page,null==b||!1===b?b:b.tplRoot),"function"===typeof b?b.apply(a):b))+'/images/free.gif" alt="'+h((f=d.l10n||a&&a.l10n||c,f.call(a,"leavemessage.close",{name:"l10n",hash:{},data:e})))+
'" />\n    </a>\n</div>\n<div class="messagetxt">'+h((f=d.l10n||a&&a.l10n||c,f.call(a,"leavemessage.descr",{name:"l10n",hash:{},data:e})))+"</div>"},useData:!0});l.leave_message_form=k({1:function(a,d,c,e){return(a=d["if"].call(a,a&&a.groupId,{name:"if",hash:{},fn:this.program(2,e),inverse:this.noop,data:e}))||0===a?a:""},2:function(a,d,c,e){var b;c=this.escapeExpression;return'<input type="hidden" name="group" value="'+c((b=d.groupId||a&&a.groupId,"function"===typeof b?b.call(a,{name:"groupId",hash:{},
data:e}):b))+'"/>'},4:function(a,d,c,e){var b,f=d.helperMissing,h=this.escapeExpression,g='\n        <tr>\n            <td class="text"><strong>'+h((b=d.l10n||a&&a.l10n||f,b.call(a,"form.field.department",{name:"l10n",hash:{},data:e})))+'</strong></td>\n            <td>\n                <select name="group" style="min-width:200px;">\n                    ';if((c=d.each.call(a,a&&a.groups,{name:"each",hash:{},fn:this.program(5,e),inverse:this.noop,data:e}))||0===c)g+=c;g+='\n                </select>\n            </td>\n        </tr>\n        <tr>\n            <td class="text"><strong>'+
h((b=d.l10n||a&&a.l10n||f,b.call(a,"form.field.department.description",{name:"l10n",hash:{},data:e})))+'</strong></td>\n            <td class="text" id="groupDescription">\n                ';if((c=d.each.call(a,a&&a.groups,{name:"each",hash:{},fn:this.program(8,e),inverse:this.noop,data:e}))||0===c)g+=c;return g+"\n            </td>\n        </tr>\n    "},5:function(a,d,c,e){var b;c=this.escapeExpression;var f='\n                        <option value="'+c((b=a&&a.id,"function"===typeof b?b.apply(a):
b))+'" ';if((b=d["if"].call(a,a&&a.selected,{name:"if",hash:{},fn:this.program(6,e),inverse:this.noop,data:e}))||0===b)f+=b;return f+">"+c((b=a&&a.name,"function"===typeof b?b.apply(a):b))+"</option>\n                    "},6:function(a,d,c,e){return'selected="selected"'},8:function(a,d,c,e){return(a=d["if"].call(a,a&&a.selected,{name:"if",hash:{},fn:this.program(9,e),inverse:this.noop,data:e}))||0===a?a:""},9:function(a,d,c,e){var b;d=this.escapeExpression;return d((b=a&&a.description,"function"===
typeof b?b.apply(a):b))},11:function(a,d,c,e){return'\n        <tr>\n            <td><img id="captcha-img" src="captcha.php"/></td>\n            <td><input type="text" name="captcha" size="50" maxlength="15" value="" class="username"/></td>\n        </tr>\n    '},compiler:[5,">= 2.0.0"],main:function(a,d,c,e){var b,f;c=this.escapeExpression;var h=d.helperMissing,g='<form name="leaveMessageForm" method="post" action="">\n    <input type="hidden" name="style" value="'+c((b=(b=a&&a.page,null==b||!1===
b?b:b.style),"function"===typeof b?b.apply(a):b))+'"/>\n    <input type="hidden" name="info" value="'+c((f=d.info||a&&a.info,"function"===typeof f?f.call(a,{name:"info",hash:{},data:e}):f))+'"/>\n    <input type="hidden" name="referrer" value="'+c((f=d.referrer||a&&a.referrer,"function"===typeof f?f.call(a,{name:"referrer",hash:{},data:e}):f))+'"/>\n    ';if((b=d.unless.call(a,a&&a.groups,{name:"unless",hash:{},fn:this.program(1,e),inverse:this.noop,data:e}))||0===b)g+=b;g+='\n\n    <div class="errors"></div>\n\n    <table cellspacing="1" cellpadding="5" border="0" class="form">\n        <tr>\n            <td><strong>'+
c((f=d.l10n||a&&a.l10n||h,f.call(a,"form.field.email",{name:"l10n",hash:{},data:e})))+':</strong></td>\n            <td><input type="text" name="email" size="50" value="'+c((f=d.email||a&&a.email,"function"===typeof f?f.call(a,{name:"email",hash:{},data:e}):f))+'" class="username"/></td>\n        </tr>\n        <tr>\n            <td><strong>'+c((f=d.l10n||a&&a.l10n||h,f.call(a,"form.field.name",{name:"l10n",hash:{},data:e})))+':</strong></td>\n            <td><input type="text" name="name" size="50" value="'+
c((f=d.name||a&&a.name,"function"===typeof f?f.call(a,{name:"name",hash:{},data:e}):f))+'" class="username"/></td>\n        </tr>\n    ';if((b=d["if"].call(a,a&&a.groups,{name:"if",hash:{},fn:this.program(4,e),inverse:this.noop,data:e}))||0===b)g+=b;g+="\n        <tr>\n            <td><strong>"+c((f=d.l10n||a&&a.l10n||h,f.call(a,"form.field.message",{name:"l10n",hash:{},data:e})))+':</strong></td>\n            <td valign="top">\n                <textarea name="message" tabindex="0" cols="40" rows="5">'+
c((f=d.message||a&&a.message,"function"===typeof f?f.call(a,{name:"message",hash:{},data:e}):f))+"</textarea>\n            </td>\n        </tr>\n    ";if((b=d["if"].call(a,a&&a.showCaptcha,{name:"if",hash:{},fn:this.program(11,e),inverse:this.noop,data:e}))||0===b)g+=b;return g+'\n    </table>\n    <a href="javascript:void(0);" class="but" id="send-message">'+c((f=d.l10n||a&&a.l10n||h,f.call(a,"mailthread.perform",{name:"l10n",hash:{},data:e})))+'</a>\n    <div class="clear">&nbsp;</div>\n</form>\n<div id="ajax-loader"><img src="'+
c((b=(b=a&&a.page,null==b||!1===b?b:b.tplRoot),"function"===typeof b?b.apply(a):b))+'/images/ajax-loader.gif" alt="Loading..." /></div>'},useData:!0});l.leave_message_layout=k({compiler:[5,">= 2.0.0"],main:function(a,d,c,e){var b="\n";if((a=this.invokePartial(c._logo,"_logo",a,void 0,d,c,e))||0===a)b+=a;return b+'\n\n\n<div id="headers">\n    <div class="wndb"><div class="wndl"><div class="wndr"><div class="wndt"><div class="wndtl"><div class="wndtr"><div class="wndbl"><div class="wndbr" id="description-region">\n    </div></div></div></div></div></div></div></div>\n</div>\n\n\n<div id="content-wrapper"></div>'},
usePartial:!0,useData:!0});l.leave_message_sent_description=k({compiler:[5,">= 2.0.0"],main:function(a,d,c,e){var b,f;c=d.helperMissing;var h=this.escapeExpression;return'<div class="buttons">\n        <a href="javascript:window.close();" title="'+h((f=d.l10n||a&&a.l10n||c,f.call(a,"chat.mailthread.sent.close",{name:"l10n",hash:{},data:e})))+'">\n            <img class="tpl-image iclosewin" src="'+h((b=(b=a&&a.page,null==b||!1===b?b:b.tplRoot),"function"===typeof b?b.apply(a):b))+'/images/free.gif" alt="'+
h((f=d.l10n||a&&a.l10n||c,f.call(a,"chat.mailthread.sent.close",{name:"l10n",hash:{},data:e})))+'" />\n        </a>\n</div>\n<div class="messagetxt">'+h((f=d.l10n||a&&a.l10n||c,f.call(a,"leavemessage.sent.message",{name:"l10n",hash:{},data:e})))+"</div>"},useData:!0});l.message=k({1:function(a,d,c,e){var b;c=this.escapeExpression;return"<span class='n"+c((b=d.kindName||a&&a.kindName,"function"===typeof b?b.call(a,{name:"kindName",hash:{},data:e}):b))+"'>"+c((b=d.name||a&&a.name,"function"===typeof b?
b.call(a,{name:"name",hash:{},data:e}):b))+"</span>: "},3:function(a,d,c,e){var b;c=d.helperMissing;var f=this.escapeExpression;return f((b=d.apply||a&&a.apply||c,b.call(a,a&&a.message,"urlReplace, nl2br, allowTags",{name:"apply",hash:{},data:e})))},5:function(a,d,c,e){var b;c=d.helperMissing;var f=this.escapeExpression;return f((b=d.apply||a&&a.apply||c,b.call(a,a&&a.message,"urlReplace, nl2br",{name:"apply",hash:{},data:e})))},compiler:[5,">= 2.0.0"],main:function(a,d,c,e){var b,f;b=d.helperMissing;
c=this.escapeExpression;var h="<span>"+c((f=d.formatTime||a&&a.formatTime||b,f.call(a,a&&a.created,{name:"formatTime",hash:{},data:e})))+"</span>\n";if((b=d["if"].call(a,a&&a.name,{name:"if",hash:{},fn:this.program(1,e),inverse:this.noop,data:e}))||0===b)h+=b;h+="\n<span class='m"+c((f=d.kindName||a&&a.kindName,"function"===typeof f?f.call(a,{name:"kindName",hash:{},data:e}):f))+"'>";if((b=d["if"].call(a,a&&a.allowFormatting,{name:"if",hash:{},fn:this.program(3,e),inverse:this.program(5,e),data:e}))||
0===b)h+=b;return h+"</span><br/>"},useData:!0});l.survey_form=k({1:function(a,d,c,e){var b;c=this.escapeExpression;return'<input type="hidden" name="email" value="'+c((b=d.email||a&&a.email,"function"===typeof b?b.call(a,{name:"email",hash:{},data:e}):b))+'"/>'},3:function(a,d,c,e){return(a=d["if"].call(a,a&&a.groupId,{name:"if",hash:{},fn:this.program(4,e),inverse:this.noop,data:e}))||0===a?a:""},4:function(a,d,c,e){var b;c=this.escapeExpression;return'<input type="hidden" name="group" value="'+
c((b=d.groupId||a&&a.groupId,"function"===typeof b?b.call(a,{name:"groupId",hash:{},data:e}):b))+'"/>'},6:function(a,d,c,e){var b;c=this.escapeExpression;return'<input type="hidden" name="message" value="'+c((b=d.message||a&&a.message,"function"===typeof b?b.call(a,{name:"message",hash:{},data:e}):b))+'"/>'},8:function(a,d,c,e){var b,f=d.helperMissing,h=this.escapeExpression,g="\n        <tr>\n            <td><strong>"+h((b=d.l10n||a&&a.l10n||f,b.call(a,"form.field.department",{name:"l10n",hash:{},
data:e})))+'</strong></td>\n            <td>\n                <select name="group">\n                    ';if((c=d.each.call(a,a&&a.groups,{name:"each",hash:{},fn:this.program(9,e),inverse:this.noop,data:e}))||0===c)g+=c;g+="\n                </select>\n            </td>\n        </tr>\n        <tr>\n            <td><strong>"+h((b=d.l10n||a&&a.l10n||f,b.call(a,"form.field.department.description",{name:"l10n",hash:{},data:e})))+'</strong></td>\n            <td id="groupDescription">';if((c=d.each.call(a,
a&&a.groups,{name:"each",hash:{},fn:this.program(14,e),inverse:this.noop,data:e}))||0===c)g+=c;return g+"</td>\n        </tr>\n    "},9:function(a,d,c,e){var b;c=this.escapeExpression;var f='\n                        <option value="'+c((b=a&&a.id,"function"===typeof b?b.apply(a):b))+'" ';if((b=d["if"].call(a,a&&a.selected,{name:"if",hash:{},fn:this.program(10,e),inverse:this.noop,data:e}))||0===b)f+=b;f+=">"+c((b=a&&a.name,"function"===typeof b?b.apply(a):b));if((b=d.unless.call(a,a&&a.online,{name:"unless",
hash:{},fn:this.program(12,e),inverse:this.noop,data:e}))||0===b)f+=b;return f+"</option>\n                    "},10:function(a,d,c,e){return'selected="selected"'},12:function(a,d,c,e){return" (offline)"},14:function(a,d,c,e){return(a=d["if"].call(a,a&&a.selected,{name:"if",hash:{},fn:this.program(15,e),inverse:this.noop,data:e}))||0===a?a:""},15:function(a,d,c,e){var b;d=this.escapeExpression;return d((b=a&&a.description,"function"===typeof b?b.apply(a):b))},17:function(a,d,c,e){return'disabled="disabled"'},
19:function(a,d,c,e){var b;c=d.helperMissing;var f=this.escapeExpression;return"\n        <tr>\n            <td><strong>"+f((b=d.l10n||a&&a.l10n||c,b.call(a,"presurvey.mail",{name:"l10n",hash:{},data:e})))+'</strong></td>\n            <td><input type="text" name="email" size="50" value="'+f((b=d.email||a&&a.email,"function"===typeof b?b.call(a,{name:"email",hash:{},data:e}):b))+'" class="username"/></td>\n        </tr>\n    '},21:function(a,d,c,e){var b;c=d.helperMissing;var f=this.escapeExpression;
return"\n        <tr>\n            <td><strong>"+f((b=d.l10n||a&&a.l10n||c,b.call(a,"presurvey.question",{name:"l10n",hash:{},data:e})))+'</strong></td>\n            <td valign="top"><textarea name="message" tabindex="0" cols="45" rows="2">'+f((b=d.message||a&&a.message,"function"===typeof b?b.call(a,{name:"message",hash:{},data:e}):b))+"</textarea></td>\n        </tr>\n    "},compiler:[5,">= 2.0.0"],main:function(a,d,c,e){var b,f;c=this.escapeExpression;var h=d.helperMissing,g='<form name="surveyForm" method="post" action="">\n    <input type="hidden" name="style" value="'+
c((b=(b=a&&a.page,null==b||!1===b?b:b.style),"function"===typeof b?b.apply(a):b))+'"/>\n    <input type="hidden" name="info" value="'+c((f=d.info||a&&a.info,"function"===typeof f?f.call(a,{name:"info",hash:{},data:e}):f))+'"/>\n    <input type="hidden" name="referrer" value="'+c((f=d.referrer||a&&a.referrer,"function"===typeof f?f.call(a,{name:"referrer",hash:{},data:e}):f))+'"/>\n    <input type="hidden" name="survey" value="on"/>\n    ';if((b=d.unless.call(a,a&&a.showEmail,{name:"unless",hash:{},
fn:this.program(1,e),inverse:this.noop,data:e}))||0===b)g+=b;g+="\n    ";if((b=d.unless.call(a,a&&a.groups,{name:"unless",hash:{},fn:this.program(3,e),inverse:this.noop,data:e}))||0===b)g+=b;g+="\n    ";if((b=d.unless.call(a,a&&a.showMessage,{name:"unless",hash:{},fn:this.program(6,e),inverse:this.noop,data:e}))||0===b)g+=b;g+='\n\n    <div class="errors"></div>\n\n    <table class="form">\n    ';if((b=d["if"].call(a,a&&a.groups,{name:"if",hash:{},fn:this.program(8,e),inverse:this.noop,data:e}))||
0===b)g+=b;g+="\n        <tr>\n            <td><strong>"+c((f=d.l10n||a&&a.l10n||h,f.call(a,"presurvey.name",{name:"l10n",hash:{},data:e})))+'</strong></td>\n            <td><input type="text" name="name" size="50" value="'+c((f=d.name||a&&a.name,"function"===typeof f?f.call(a,{name:"name",hash:{},data:e}):f))+'" class="username" ';if((b=d.unless.call(a,a&&a.canChangeName,{name:"unless",hash:{},fn:this.program(17,e),inverse:this.noop,data:e}))||0===b)g+=b;g+="/></td>\n        </tr>\n    ";if((b=d["if"].call(a,
a&&a.showEmail,{name:"if",hash:{},fn:this.program(19,e),inverse:this.noop,data:e}))||0===b)g+=b;g+="\n    ";if((b=d["if"].call(a,a&&a.showMessage,{name:"if",hash:{},fn:this.program(21,e),inverse:this.noop,data:e}))||0===b)g+=b;return g+'\n    </table>\n    <a href="javascript:void(0);" class="but" id="submit-survey">'+c((f=d.l10n||a&&a.l10n||h,f.call(a,"presurvey.submit",{name:"l10n",hash:{},data:e})))+'</a>\n    <div class="clear">&nbsp;</div>\n</form>\n<div id="ajax-loader"><img src="'+c((b=(b=
a&&a.page,null==b||!1===b?b:b.tplRoot),"function"===typeof b?b.apply(a):b))+'/images/ajax-loader.gif" alt="Loading..." /></div>'},useData:!0});l.survey_layout=k({compiler:[5,">= 2.0.0"],main:function(a,d,c,e){var b,f=d.helperMissing,h=this.escapeExpression,g="\n";if((c=this.invokePartial(c._logo,"_logo",a,void 0,d,c,e))||0===c)g+=c;return g+'\n\n\n<div id="headers">\n    <div class="wndb"><div class="wndl"><div class="wndr"><div class="wndt"><div class="wndtl"><div class="wndtr"><div class="wndbl"><div class="wndbr">\n        <div class="buttons">\n            <a href="javascript:window.close();" title="'+
h((b=d.l10n||a&&a.l10n||f,b.call(a,"leavemessage.close",{name:"l10n",hash:{},data:e})))+'"><img class="tpl-image iclosewin" src="'+h((c=(c=a&&a.page,null==c||!1===c?c:c.tplRoot),"function"===typeof c?c.apply(a):c))+'/images/free.gif" alt="'+h((b=d.l10n||a&&a.l10n||f,b.call(a,"leavemessage.close",{name:"l10n",hash:{},data:e})))+'" /></a>\n        </div>\n        <div class="messagetxt">'+h((b=d.l10n||a&&a.l10n||f,b.call(a,"presurvey.intro",{name:"l10n",hash:{},data:e})))+'</div>\n    </div></div></div></div></div></div></div></div>\n</div>\n\n\n<div id="content-wrapper"></div>'},
usePartial:!0,useData:!0})})();
