/*
 Copyright 2005-2014 the original author or authors.

 Licensed under the Apache License, Version 2.0 (the "License").
 You may obtain a copy of the License at
     http://www.apache.org/licenses/LICENSE-2.0
*/
function MibewAPI(a){this.protocolVersion="1.0";if("object"!=typeof a||!(a instanceof MibewAPIInteraction))throw Error("Wrong interaction type");this.interaction=a}
MibewAPI.prototype.checkFunction=function(a,b){if("undefined"==typeof a["function"]||""==a["function"])throw Error("Cannot call for function with no name");if(b)for(var d=this.interaction.getReservedFunctionsNames(),c=0;c<d.length;c++)if(a["function"]==d[c])throw Error("'"+a["function"]+"' is reserved function name");if("object"!=typeof a.arguments)throw Error("There are no arguments in '"+a["function"]+"' function");var d=0,f=this.interaction.getMandatoryArguments(a["function"]),e;a:for(e in a.arguments)for(c=
0;c<f.length;c++)if(e==f[c]){d++;continue a}if(d!=f.length)throw Error("Not all mandatory arguments are set in '"+a["function"]+"' function");};MibewAPI.prototype.checkRequest=function(a){if("string"!=typeof a.token){if("undefined"==typeof a.token)throw Error("Empty token");throw Error("Wrong token type");}if(""==a.token)throw Error("Empty token");if("object"!=typeof a.functions||!(a.functions instanceof Array)||0==a.functions.length)throw Error("Empty functions set");for(var b=0;b<a.functions.length;b++)this.checkFunction(a.functions[b])};
MibewAPI.prototype.checkPackage=function(a){if("undefined"==typeof a.signature)throw Error("Missed package signature");if("undefined"==typeof a.proto)throw Error("Missed protocol version");if(a.proto!=this.protocolVersion)throw Error("Wrong protocol version");if("undefined"==typeof a.async)throw Error("'async' flag is missed");if("boolean"!=typeof a.async)throw Error("Wrong 'async' flag value");if("object"!=typeof a.requests||!(a.requests instanceof Array)||0==a.requests.length)throw Error("Empty requests set");
for(var b=0;b<a.requests.length;b++)this.checkRequest(a.requests[b])};MibewAPI.prototype.getResultFunction=function(a,b){"undefined"==typeof b&&(b=null);var d=null,c;for(c in a)if(a.hasOwnProperty(c)&&"result"==a[c]["function"]){if(null!==d)throw Error("Function 'result' already exists in functions list");d=a[c]}if(!0===b&&null===d)throw Error("There is no 'result' function in functions list");if(!1===b&&null!==d)throw Error("There is 'result' function in functions list");return d};
MibewAPI.prototype.buildResult=function(a,b){var d=this.interaction.getMandatoryArgumentsDefaults("result"),c;for(c in d)d.hasOwnProperty(c)&&(a[c]=d[c]);return{token:b,functions:[{"function":"result",arguments:a}]}};MibewAPI.prototype.encodePackage=function(a){var b={signature:""};b.proto=this.protocolVersion;b.async=!0;b.requests=a;return encodeURIComponent(JSON.stringify(b)).replace(/\%20/gi,"+")};
MibewAPI.prototype.decodePackage=function(a){a=JSON.parse(decodeURIComponent(a.replace(/\+/gi," ")));this.checkPackage(a);return a};function MibewAPIInteraction(){this.mandatoryArguments=function(){return{}};this.getReservedFunctionsNames=function(){return[]}}
MibewAPIInteraction.prototype.getMandatoryArguments=function(a){var b=this.mandatoryArguments(),d=[];if("object"==typeof b["*"])for(var c in b["*"])b["*"].hasOwnProperty(c)&&d.push(c);if("object"==typeof b[a])for(c in b[a])b[a].hasOwnProperty(c)&&d.push(c);return d};
MibewAPIInteraction.prototype.getMandatoryArgumentsDefaults=function(a){var b=this.mandatoryArguments(),d={};if("object"==typeof b["*"])for(var c in b["*"])b["*"].hasOwnProperty(c)&&(d[c]=b["*"][c]);if("object"==typeof b[a])for(c in b[a])b[a].hasOwnProperty(c)&&(d[c]=b[a][c]);return d};function MibewAPIExecutionContext(){this.returnValues={};this.functionsResults=[]}
MibewAPIExecutionContext.prototype.getArgumentsList=function(a){var b=a.arguments,d=a.arguments.references,c,f,e;for(e in d)if(d.hasOwnProperty(e)){f=d[e];if("undefined"==typeof this.functionsResults[f-1])throw Error("Wrong reference in '"+a["function"]+"' function. Function #"+f+" does not call yet.");if("undefined"==typeof b[e]||""==b[e])throw Error("Wrong reference in '"+a["function"]+"' function. Empty '"+e+"' argument.");c=b[e];if("undefined"==typeof this.functionsResults[f-1][c])throw Error("Wrong reference in '"+
a["function"]+"' function. There is no '"+c+"' argument in #"+f+" function results");b[e]=this.functionsResults[f-1][c]}return b};MibewAPIExecutionContext.prototype.getResults=function(){return this.returnValues};
MibewAPIExecutionContext.prototype.storeFunctionResults=function(a,b){var d;if(b.errorCode)this.returnValues.errorCode=b.errorCode,this.returnValues.errorMessage=b.errorMessage||"";else for(var c in a.arguments["return"])if(a.arguments["return"].hasOwnProperty(c)){d=a.arguments["return"][c];if("undefined"==typeof b[c])throw Error("Variable with name '"+c+"' is undefined in the results of the '"+a["function"]+"' function");this.returnValues[d]=b[c]}this.functionsResults.push(b)};
