/*
 This file is part of Mibew Messenger project.
 http://mibew.org
 Copyright (c) 2005-2011 Mibew Messenger Community
 License: http://mibew.org/license.php
*/
(function(){var k=Handlebars.template,l=Handlebars.templates=Handlebars.templates||{};l.agent=k(function(d,b,e,a,c){this.compilerInfo=[2,">= 1.0.0-rc.3"];e=e||d.helpers;c=c||{};var f=e.helperMissing,g=this.escapeExpression;d='<span class="agent-status-';if((a=e["if"].call(b,b.away,{hash:{},inverse:this.program(3,function(){return"online"},c),fn:this.program(1,function(){return"away"},c),data:c}))||0===a)d+=a;d+=' inline-block" title="';if((a=e["if"].call(b,b.away,{hash:{},inverse:this.program(7,function(a,
d){var b,m;m={hash:{},data:d};return g((b=e.L10n,b?b.call(a,"pending.status.online",m):f.call(a,"L10n","pending.status.online",m)))},c),fn:this.program(5,function(a,d){var b,m;m={hash:{},data:d};return g((b=e.L10n,b?b.call(a,"pending.status.away",m):f.call(a,"L10n","pending.status.away",m)))},c),data:c}))||0===a)d+=a;d+='"></span>';(a=e.name)?a=a.call(b,{hash:{},data:c}):(a=b.name,a="function"===typeof a?a.apply(b):a);d+=g(a);if((a=e.unless.call(b,b.isLast,{hash:{},inverse:this.noop,fn:this.program(9,
function(){return","},c),data:c}))||0===a)d+=a;return d});l.no_threads=k(function(d,b,e,a,c){this.compilerInfo=[2,">= 1.0.0-rc.3"];e=e||d.helpers;c=c||{};var f;d=e.helperMissing;a=this.escapeExpression;c={hash:{},data:c};return b='<td class="no-threads" colspan="8">'+(a((f=e.L10n,f?f.call(b,"clients.no_clients",c):d.call(b,"L10n","clients.no_clients",c)))+"</td>")});l.no_visitors=k(function(d,b,e,a,c){this.compilerInfo=[2,">= 1.0.0-rc.3"];e=e||d.helpers;c=c||{};var f;d=e.helperMissing;a=this.escapeExpression;
c={hash:{},data:c};return b='<td class="no-visitors" colspan="9">'+(a((f=e.L10n,f?f.call(b,"visitors.no_visitors",c):d.call(b,"L10n","visitors.no_visitors",c)))+"</td>")});l.status_panel=k(function(d,b,e,a,c){this.compilerInfo=[2,">= 1.0.0-rc.3"];e=e||d.helpers;c=c||{};var f,g=e.helperMissing,h=this.escapeExpression;d='<div id="connstatus">';(a=e.message)?a=a.call(b,{hash:{},data:c}):(a=b.message,a="function"===typeof a?a.apply(b):a);d+=h(a);if((f=e["if"].call(b,(a=b.agent,null==a||!1===a?a:a.away),
{hash:{},inverse:this.program(3,function(a,d){var b,c;c={hash:{},data:d};return h((b=e.L10n,b?b.call(a,"pending.status.online",c):g.call(a,"L10n","pending.status.online",c)))},c),fn:this.program(1,function(a,d){var b,c;c={hash:{},data:d};return h((b=e.L10n,b?b.call(a,"pending.status.away",c):g.call(a,"L10n","pending.status.away",c)))},c),data:c}))||0===f)d+=f;d+='</div><div id="connlinks"><a href="javascript:void(0);" id="change-status">';if((f=e["if"].call(b,(a=b.agent,null==a||!1===a?a:a.away),
{hash:{},inverse:this.program(7,function(a,d){var b,c;c={hash:{},data:d};return h((b=e.L10n,b?b.call(a,"pending.status.setaway",c):g.call(a,"L10n","pending.status.setaway",c)))},c),fn:this.program(5,function(a,d){var b,c;c={hash:{},data:d};return h((b=e.L10n,b?b.call(a,"pending.status.setonline",c):g.call(a,"L10n","pending.status.setonline",c)))},c),data:c}))||0===f)d+=f;return d+"</a></div>"});l.threads_collection=k(function(d,b,e,a,c){this.compilerInfo=[2,">= 1.0.0-rc.3"];e=e||d.helpers;c=c||{};
var f,g=e.helperMissing,h=this.escapeExpression;a={hash:{},data:c};d='<table class="awaiting" border="0">\n<thead>\n<tr>\n    <th class="first">'+(h((f=e.L10n,f?f.call(b,"pending.table.head.name",a):g.call(b,"L10n","pending.table.head.name",a)))+"</th>\n    <th>");a={hash:{},data:c};d+=h((f=e.L10n,f?f.call(b,"pending.table.head.actions",a):g.call(b,"L10n","pending.table.head.actions",a)))+"</th>\n    <th>";a={hash:{},data:c};d+=h((f=e.L10n,f?f.call(b,"pending.table.head.contactid",a):g.call(b,"L10n",
"pending.table.head.contactid",a)))+"</th>\n    <th>";a={hash:{},data:c};d+=h((f=e.L10n,f?f.call(b,"pending.table.head.state",a):g.call(b,"L10n","pending.table.head.state",a)))+"</th>\n    <th>";a={hash:{},data:c};d+=h((f=e.L10n,f?f.call(b,"pending.table.head.operator",a):g.call(b,"L10n","pending.table.head.operator",a)))+"</th>\n    <th>";a={hash:{},data:c};d+=h((f=e.L10n,f?f.call(b,"pending.table.head.total",a):g.call(b,"L10n","pending.table.head.total",a)))+"</th>\n    <th>";a={hash:{},data:c};
d+=h((f=e.L10n,f?f.call(b,"pending.table.head.waittime",a):g.call(b,"L10n","pending.table.head.waittime",a)))+"</th>\n    <th>";a={hash:{},data:c};return d+=h((f=e.L10n,f?f.call(b,"pending.table.head.etc",a):g.call(b,"L10n","pending.table.head.etc",a)))+'</th>\n</tr>\n</thead>\n<tbody id="threads-container">\n\n</tbody>\n</table>'});l.visitors_collection=k(function(d,b,e,a,c){this.compilerInfo=[2,">= 1.0.0-rc.3"];e=e||d.helpers;c=c||{};var f,g=e.helperMissing,h=this.escapeExpression;a={hash:{},data:c};
d='<table id="visitorslist" class="awaiting" border="0">\n<thead>\n<tr>\n    <th class="first">'+(h((f=e.L10n,f?f.call(b,"visitors.table.head.name",a):g.call(b,"L10n","visitors.table.head.name",a)))+"</th>\n    <th>");a={hash:{},data:c};d+=h((f=e.L10n,f?f.call(b,"visitors.table.head.actions",a):g.call(b,"L10n","visitors.table.head.actions",a)))+"</th>\n    <th>";a={hash:{},data:c};d+=h((f=e.L10n,f?f.call(b,"visitors.table.head.contactid",a):g.call(b,"L10n","visitors.table.head.contactid",a)))+"</th>\n    <th>";
a={hash:{},data:c};d+=h((f=e.L10n,f?f.call(b,"visitors.table.head.firsttimeonsite",a):g.call(b,"L10n","visitors.table.head.firsttimeonsite",a)))+"</th>\n    <th>";a={hash:{},data:c};d+=h((f=e.L10n,f?f.call(b,"visitors.table.head.lasttimeonsite",a):g.call(b,"L10n","visitors.table.head.lasttimeonsite",a)))+"</th>\n    <th>";a={hash:{},data:c};d+=h((f=e.L10n,f?f.call(b,"visitors.table.head.invited.by",a):g.call(b,"L10n","visitors.table.head.invited.by",a)))+"</th>\n    <th>";a={hash:{},data:c};d+=h((f=
e.L10n,f?f.call(b,"visitors.table.head.invitationtime",a):g.call(b,"L10n","visitors.table.head.invitationtime",a)))+"</th>\n    <th>";a={hash:{},data:c};d+=h((f=e.L10n,f?f.call(b,"visitors.table.head.invitations",a):g.call(b,"L10n","visitors.table.head.invitations",a)))+"</th>\n    <th>";a={hash:{},data:c};return d+=h((f=e.L10n,f?f.call(b,"visitors.table.head.etc",a):g.call(b,"L10n","visitors.table.head.etc",a)))+'</th>\n</tr>\n</thead>\n<tbody id="visitors-container">\n</tbody>\n</table>'});l.queued_thread=
k(function(d,b,e,a,c){this.compilerInfo=[2,">= 1.0.0-rc.3"];e=e||d.helpers;c=c||{};var f=e.helperMissing,g=this.escapeExpression;d='<td class="visitor">\n    <div><a href="javascript:void(0);" class="user-name open-dialog" title="';if((a=e["if"].call(b,b.canOpen,{hash:{},inverse:this.program(3,function(a,d){var b,c;c={hash:{},data:d};return g((b=e.L10n,b?b.call(a,"pending.table.view",c):f.call(a,"L10n","pending.table.view",c)))},c),fn:this.program(1,function(a,d){var b,c;c={hash:{},data:d};return g((b=
e.L10n,b?b.call(a,"pending.table.speak",c):f.call(a,"L10n","pending.table.speak",c)))},c),data:c}))||0===a)d+=a;d+='">';if((a=e["if"].call(b,b.ban,{hash:{},inverse:this.noop,fn:this.program(5,function(a,d){var b,c;b={hash:{},data:d};return b=""+(g((c=e.L10n,c?c.call(a,"chat.client.spam.prefix",b):f.call(a,"L10n","chat.client.spam.prefix",b)))+"&nbsp;")},c),data:c}))||0===a)d+=a;(a=e.userName)?a=a.call(b,{hash:{},data:c}):(a=b.userName,a="function"===typeof a?a.apply(b):a);d+=g(a)+"</a></div>\n    ";
if((a=e["if"].call(b,b.firstMessage,{hash:{},inverse:this.noop,fn:this.program(7,function(a,d){var b,c;b='<div class="first-message"><a href="javascript:void(0);" title="';(c=e.firstMessage)?c=c.call(a,{hash:{},data:d}):(c=a.firstMessage,c="function"===typeof c?c.apply(a):c);b+=g(c)+'">';(c=e.firstMessagePreview)?c=c.call(a,{hash:{},data:d}):(c=a.firstMessagePreview,c="function"===typeof c?c.apply(a):c);return b+=g(c)+"</a></div>"},c),data:c}))||0===a)d+=a;d+='\n</td>\n<td class="visitor">\n    <div class="default-thread-controls inline-block">\n        ';
if((a=e["if"].call(b,b.canOpen,{hash:{},inverse:this.noop,fn:this.program(9,function(a,d){var b,c;b={hash:{},data:d};return b='\n            <div class="control open-dialog open-control inline-block" title="'+(g((c=e.L10n,c?c.call(a,"pending.table.speak",b):f.call(a,"L10n","pending.table.speak",b)))+'"></div>\n        ')},c),data:c}))||0===a)d+=a;d+="\n        ";if((a=e["if"].call(b,b.canView,{hash:{},inverse:this.noop,fn:this.program(11,function(a,d){var b,c;b={hash:{},data:d};return b='\n            <div class="control view-control inline-block" title="'+
(g((c=e.L10n,c?c.call(a,"pending.table.view",b):f.call(a,"L10n","pending.table.view",b)))+'"></div>\n        ')},c),data:c}))||0===a)d+=a;d+="\n        ";if((a=e["if"].call(b,b.tracked,{hash:{},inverse:this.noop,fn:this.program(13,function(a,d){var b,c;b={hash:{},data:d};return b='\n            <div class="control track-control inline-block" title="'+(g((c=e.L10n,c?c.call(a,"pending.table.tracked",b):f.call(a,"L10n","pending.table.tracked",b)))+'"></div>\n        ')},c),data:c}))||0===a)d+=a;d+="\n        ";
if((a=e["if"].call(b,b.canBan,{hash:{},inverse:this.noop,fn:this.program(15,function(a,b){var d,c;d={hash:{},data:b};return d='\n            <div class="control ban-control inline-block" title="'+(g((c=e.L10n,c?c.call(a,"pending.table.ban",d):f.call(a,"L10n","pending.table.ban",d)))+'"></div>\n        ')},c),data:c}))||0===a)d+=a;d+='\n    </div>\n    <div class="thread-controls inline-block"></div>\n</td>\n<td class="visitor">';if((a=e["if"].call(b,b.userIp,{hash:{},inverse:this.program(19,function(a,
d){var b;(b=e.remote)?b=b.call(a,{hash:{},data:d}):(b=a.remote,b="function"===typeof b?b.apply(a):b);return g(b)},c),fn:this.program(17,function(a,b){var d,c;d='<a href="javascript:void(0);" class="geo-link" title="GeoLocation">';(c=e.remote)?c=c.call(a,{hash:{},data:b}):(c=a.remote,c="function"===typeof c?c.apply(a):c);return d+=g(c)+"</a>"},c),data:c}))||0===a)d+=a;d+='</td>\n<td class="visitor">';(a=e.stateDesc)?a=a.call(b,{hash:{},data:c}):(a=b.stateDesc,a="function"===typeof a?a.apply(b):a);
d+=g(a)+'</td>\n<td class="visitor">';(a=e.agentName)?a=a.call(b,{hash:{},data:c}):(a=b.agentName,a="function"===typeof a?a.apply(b):a);d+=g(a)+'</td>\n<td class="visitor"><span class="timesince" data-timestamp="';(a=e.totalTime)?a=a.call(b,{hash:{},data:c}):(a=b.totalTime,a="function"===typeof a?a.apply(b):a);d+=g(a)+'"></span></td>\n<td class="visitor">';if((a=e.unless.call(b,b.chatting,{hash:{},inverse:this.program(23,function(){return"-"},c),fn:this.program(21,function(a,b){var d,c;d='<span class="timesince" data-timestamp="';
(c=e.waitingTime)?c=c.call(a,{hash:{},data:b}):(c=a.waitingTime,c="function"===typeof c?c.apply(a):c);return d+=g(c)+'"></span>'},c),data:c}))||0===a)d+=a;d+='</td>\n<td class="visitor">';if((a=e["if"].call(b,b.ban,{hash:{},inverse:this.program(27,function(a,b){var c;(c=e.userAgent)?c=c.call(a,{hash:{},data:b}):(c=a.userAgent,c="function"===typeof c?c.apply(a):c);return g(c)},c),fn:this.program(25,function(a){var c;return g((c=(c=a.ban,null==c||!1===c?c:c.reason),"function"===typeof c?c.apply(a):
c))},c),data:c}))||0===a)d+=a;return d+"</td>"});l.visitor=k(function(d,b,e,a,c){function f(){return"-"}this.compilerInfo=[2,">= 1.0.0-rc.3"];e=e||d.helpers;c=c||{};var g,h=e.helperMissing,j=this.escapeExpression;d='<td class="visitor">\n    ';if((a=e.unless.call(b,b.invitationInfo,{hash:{},inverse:this.program(3,function(a,c){var b;(b=e.userName)?b=b.call(a,{hash:{},data:c}):(b=a.userName,b="function"===typeof b?b.apply(a):b);return j(b)},c),fn:this.program(1,function(a,c){var b,d;b={hash:{},data:c};
b='<a href="javascript:void(0);" class="invite-link" title="'+(j((d=e.L10n,d?d.call(a,"pending.table.invite",b):h.call(a,"L10n","pending.table.invite",b)))+'">');(d=e.userName)?d=d.call(a,{hash:{},data:c}):(d=a.userName,d="function"===typeof d?d.apply(a):d);return b+=j(d)+"</a>"},c),data:c}))||0===a)d+=a;g={hash:{},data:c};d=d+'\n</td>\n<td class="visitor">\n    <div class="default-visitor-controls inline-block">\n        <div class="control track-control inline-block" title="'+(j((a=e.L10n,a?a.call(b,
"pending.table.tracked",g):h.call(b,"L10n","pending.table.tracked",g)))+'"></div>\n    </div>\n    <div class="visitor-controls inline-block"></div>\n</td>\n<td class="visitor">');if((a=e["if"].call(b,b.userIp,{hash:{},inverse:this.program(7,function(a,c){var b;(b=e.remote)?b=b.call(a,{hash:{},data:c}):(b=a.remote,b="function"===typeof b?b.apply(a):b);return j(b)},c),fn:this.program(5,function(a,b){var c,d;c='<a href="javascript:void(0);" class="geo-link" title="GeoLocation">';(d=e.remote)?d=d.call(a,
{hash:{},data:b}):(d=a.remote,d="function"===typeof d?d.apply(a):d);return c+=j(d)+"</a>"},c),data:c}))||0===a)d+=a;d+='</td>\n<td class="visitor"><span class="timesince" data-timestamp="';(a=e.firstTime)?a=a.call(b,{hash:{},data:c}):(a=b.firstTime,a="function"===typeof a?a.apply(b):a);d+=j(a)+'"></span></td>\n<td class="visitor"><span class="timesince" data-timestamp="';(a=e.lastTime)?a=a.call(b,{hash:{},data:c}):(a=b.lastTime,a="function"===typeof a?a.apply(b):a);d+=j(a)+'"></span></td>\n<td class="visitor">';
if((a=e["if"].call(b,b.invitationInfo,{hash:{},inverse:this.program(11,f,c),fn:this.program(9,function(a){var b;return j((b=(b=a.invitationInfo,null==b||!1===b?b:b.agentName),"function"===typeof b?b.apply(a):b))},c),data:c}))||0===a)d+=a;d+='</td>\n<td class="visitor">';if((a=e["if"].call(b,b.invitationInfo,{hash:{},inverse:this.program(11,f,c),fn:this.program(13,function(a){var b;return a=""+('<span class="timesince" data-timestamp="'+j((b=(b=a.invitationInfo,null==b||!1===b?b:b.time),"function"===
typeof b?b.apply(a):b))+'"></span>')},c),data:c}))||0===a)d+=a;d+='</td>\n<td class="visitor">';(a=e.invitations)?a=a.call(b,{hash:{},data:c}):(a=b.invitations,a="function"===typeof a?a.apply(b):a);d+=j(a)+" / ";(a=e.chats)?a=a.call(b,{hash:{},data:c}):(a=b.chats,a="function"===typeof a?a.apply(b):a);d+=j(a)+'</td>\n<td class="visitor">';(a=e.userAgent)?a=a.call(b,{hash:{},data:c}):(a=b.userAgent,a="function"===typeof a?a.apply(b):a);return d+=j(a)+"</td>"})})();
