<?php

require_once dirname(__FILE__) . '/../../../../webim/libs/classes/plugin_manager.php';
require_once dirname(__FILE__) . '/../../../../webim/libs/classes/plugin.php';

/**
 * Test class for PluginManager.
 * Generated by PHPUnit on 2012-07-17 at 16:09:18.
 */
class PluginManagerTest extends PHPUnit_Framework_TestCase {

	public function testLoadPlugins() {
		set_include_path(get_include_path() . PATH_SEPARATOR . dirname(__FILE__));
		PluginManager::loadPlugins(
			array(
				array(
					'name' => 'phpunit_autotest_plugin_manager'
				)
			)
		);
		if(empty($GLOBALS['phpunit_autotest_plugin_manager'])) {
			$this->fail('Plugin not loaded and initialize correctly');
		}
	}

}

?>
