/*
 Copyright 2005-2014 the original author or authors.
 Licensed under the Apache License, Version 2.0 (the "License").
 You may obtain a copy of the License at
      http://www.apache.org/licenses/LICENSE-2.0
*/
(function(){var l=Handlebars.template,m=Handlebars.templates=Handlebars.templates||{};m.visitor=l(function(c,a,f,b,d){function g(a,b){return"-"}this.compilerInfo=[4,">= 1.0.0"];f=this.merge(f,c.helpers);d=d||{};var e,n,p=f.helperMissing,k=this.escapeExpression;c='<td class="visitor">\n    ';if((b=f.unless.call(a,a&&a.invitationInfo,{hash:{},inverse:this.program(3,function(a,b){var c;(c=f.userName)?c=c.call(a,{hash:{},data:b}):(c=a&&a.userName,c="function"===typeof c?c.call(a,{hash:{},data:b}):c);
return k(c)},d),fn:this.program(1,function(a,b){var c,e,d;c=""+('<a href="javascript:void(0);" class="invite-link" title="'+k((e=f.l10n||a&&a.l10n,d={hash:{},data:b},e?e.call(a,"Invite to chat",d):p.call(a,"l10n","Invite to chat",d)))+'">');(e=f.userName)?e=e.call(a,{hash:{},data:b}):(e=a&&a.userName,e="function"===typeof e?e.call(a,{hash:{},data:b}):e);return c+=k(e)+"</a>"},d),data:d}))||0===b)c+=b;c+='\n</td>\n<td class="visitor">\n    <div class="default-visitor-controls inline-block">\n        <div class="control track-control inline-block" title="'+
k((e=f.l10n||a&&a.l10n,n={hash:{},data:d},e?e.call(a,"Tracked visitor's path",n):p.call(a,"l10n","Tracked visitor's path",n)))+'"></div>\n    </div>\n    <div class="visitor-controls inline-block"></div>\n</td>\n<td class="visitor">';if((b=f["if"].call(a,a&&a.userIp,{hash:{},inverse:this.program(7,function(a,b){var c;(c=f.remote)?c=c.call(a,{hash:{},data:b}):(c=a&&a.remote,c="function"===typeof c?c.call(a,{hash:{},data:b}):c);return k(c)},d),fn:this.program(5,function(a,b){var c,e;c='<a href="javascript:void(0);" class="geo-link" title="GeoLocation">';
(e=f.remote)?e=e.call(a,{hash:{},data:b}):(e=a&&a.remote,e="function"===typeof e?e.call(a,{hash:{},data:b}):e);return c+=k(e)+"</a>"},d),data:d}))||0===b)c+=b;c+='</td>\n<td class="visitor"><span class="timesince" data-timestamp="';(e=f.firstTime)?b=e.call(a,{hash:{},data:d}):(e=a&&a.firstTime,b="function"===typeof e?e.call(a,{hash:{},data:d}):e);c+=k(b)+'"></span></td>\n<td class="visitor"><span class="timesince" data-timestamp="';(e=f.lastTime)?b=e.call(a,{hash:{},data:d}):(e=a&&a.lastTime,b="function"===
typeof e?e.call(a,{hash:{},data:d}):e);c+=k(b)+'"></span></td>\n<td class="visitor">';if((b=f["if"].call(a,a&&a.invitationInfo,{hash:{},inverse:this.program(11,g,d),fn:this.program(9,function(a,b){var c;return k((c=(c=a&&a.invitationInfo,null==c||!1===c?c:c.agentName),"function"===typeof c?c.apply(a):c))},d),data:d}))||0===b)c+=b;c+='</td>\n<td class="visitor">';if((b=f["if"].call(a,a&&a.invitationInfo,{hash:{},inverse:this.program(11,g,d),fn:this.program(13,function(a,b){var c,e;return c=""+('<span class="timesince" data-timestamp="'+
k((e=(e=a&&a.invitationInfo,null==e||!1===e?e:e.time),"function"===typeof e?e.apply(a):e))+'"></span>')},d),data:d}))||0===b)c+=b;c+='</td>\n<td class="visitor">';(e=f.invitations)?b=e.call(a,{hash:{},data:d}):(e=a&&a.invitations,b="function"===typeof e?e.call(a,{hash:{},data:d}):e);c+=k(b)+" / ";(e=f.chats)?b=e.call(a,{hash:{},data:d}):(e=a&&a.chats,b="function"===typeof e?e.call(a,{hash:{},data:d}):e);c+=k(b)+'</td>\n<td class="visitor">';(e=f.userAgent)?b=e.call(a,{hash:{},data:d}):(e=a&&a.userAgent,
b="function"===typeof e?e.call(a,{hash:{},data:d}):e);return c+=k(b)+"</td>"});m.visitors_collection=l(function(c,a,f,b,d){this.compilerInfo=[4,">= 1.0.0"];f=this.merge(f,c.helpers);d=d||{};var g,e;c=f.helperMissing;b=this.escapeExpression;return a=""+('<table id="visitorslist" class="awaiting" border="0">\n<thead>\n<tr>\n    <th class="first">'+b((g=f.l10n||a&&a.l10n,e={hash:{},data:d},g?g.call(a,"Name",e):c.call(a,"l10n","Name",e)))+"</th>\n    <th>"+b((g=f.l10n||a&&a.l10n,e={hash:{},data:d},g?
g.call(a,"Actions",e):c.call(a,"l10n","Actions",e)))+"</th>\n    <th>"+b((g=f.l10n||a&&a.l10n,e={hash:{},data:d},g?g.call(a,"Visitor's address",e):c.call(a,"l10n","Visitor's address",e)))+"</th>\n    <th>"+b((g=f.l10n||a&&a.l10n,e={hash:{},data:d},g?g.call(a,"First seen",e):c.call(a,"l10n","First seen",e)))+"</th>\n    <th>"+b((g=f.l10n||a&&a.l10n,e={hash:{},data:d},g?g.call(a,"Last seen",e):c.call(a,"l10n","Last seen",e)))+"</th>\n    <th>"+b((g=f.l10n||a&&a.l10n,e={hash:{},data:d},g?g.call(a,"Invited by",
e):c.call(a,"l10n","Invited by",e)))+"</th>\n    <th>"+b((g=f.l10n||a&&a.l10n,e={hash:{},data:d},g?g.call(a,"Invitation time",e):c.call(a,"l10n","Invitation time",e)))+"</th>\n    <th>"+b((g=f.l10n||a&&a.l10n,e={hash:{},data:d},g?g.call(a,"Invitations / Chats",e):c.call(a,"l10n","Invitations / Chats",e)))+"</th>\n    <th>"+b((g=f.l10n||a&&a.l10n,e={hash:{},data:d},g?g.call(a,"Misc",e):c.call(a,"l10n","Misc",e)))+'</th>\n</tr>\n</thead>\n<tbody id="visitors-container">\n</tbody>\n</table>')});m.agent=
l(function(c,a,f,b,d){this.compilerInfo=[4,">= 1.0.0"];f=this.merge(f,c.helpers);d=d||{};var g=f.helperMissing,e=this.escapeExpression;c='<span class="agent-status-';if((b=f["if"].call(a,a&&a.away,{hash:{},inverse:this.program(3,function(a,b){return"online"},d),fn:this.program(1,function(a,b){return"away"},d),data:d}))||0===b)c+=b;c+=' inline-block" title="';if((b=f["if"].call(a,a&&a.away,{hash:{},inverse:this.program(7,function(a,b){var c,d;return e((c=f.l10n||a&&a.l10n,d={hash:{},data:b},c?c.call(a,
"Up to date",d):g.call(a,"l10n","Up to date",d)))},d),fn:this.program(5,function(a,b){var c,d;return e((c=f.l10n||a&&a.l10n,d={hash:{},data:b},c?c.call(a,"Away",d):g.call(a,"l10n","Away",d)))},d),data:d}))||0===b)c+=b;c+='"></span>';(b=f.name)?b=b.call(a,{hash:{},data:d}):(b=a&&a.name,b="function"===typeof b?b.call(a,{hash:{},data:d}):b);c+=e(b);if((b=f.unless.call(a,a&&a.isLast,{hash:{},inverse:this.noop,fn:this.program(9,function(a,b){return","},d),data:d}))||0===b)c+=b;return c});m.no_threads=
l(function(c,a,f,b,d){this.compilerInfo=[4,">= 1.0.0"];f=this.merge(f,c.helpers);d=d||{};var g,e;c=f.helperMissing;b=this.escapeExpression;return a=""+('<td class="no-threads" colspan="8">'+b((g=f.l10n||a&&a.l10n,e={hash:{},data:d},g?g.call(a,"The list of visitors waiting is empty",e):c.call(a,"l10n","The list of visitors waiting is empty",e)))+"</td>")});m.no_visitors=l(function(c,a,f,b,d){this.compilerInfo=[4,">= 1.0.0"];f=this.merge(f,c.helpers);d=d||{};var g,e;c=f.helperMissing;b=this.escapeExpression;
return a=""+('<td class="no-visitors" colspan="9">'+b((g=f.l10n||a&&a.l10n,e={hash:{},data:d},g?g.call(a,"There are no visitors ready to chat on your site at present time",e):c.call(a,"l10n","There are no visitors ready to chat on your site at present time",e)))+"</td>")});m.queued_thread=l(function(c,a,f,b,d){this.compilerInfo=[4,">= 1.0.0"];f=this.merge(f,c.helpers);d=d||{};var g=f.helperMissing,e=this.escapeExpression;c='<td class="visitor">\n    <div><a href="javascript:void(0);" class="user-name open-dialog" title="';
if((b=f["if"].call(a,a&&a.canOpen,{hash:{},inverse:this.program(3,function(a,b){var c,d;return e((c=f.l10n||a&&a.l10n,d={hash:{},data:b},c?c.call(a,"Watch the chat",d):g.call(a,"l10n","Watch the chat",d)))},d),fn:this.program(1,function(a,b){var c,d;return e((c=f.l10n||a&&a.l10n,d={hash:{},data:b},c?c.call(a,"Click to chat with the visitor",d):g.call(a,"l10n","Click to chat with the visitor",d)))},d),data:d}))||0===b)c+=b;c+='">';if((b=f["if"].call(a,a&&a.ban,{hash:{},inverse:this.noop,fn:this.program(5,
function(a,b){var c,d,h;return c=""+(e((d=f.l10n||a&&a.l10n,h={hash:{},data:b},d?d.call(a,"[spam]",h):g.call(a,"l10n","[spam]",h)))+"&nbsp;")},d),data:d}))||0===b)c+=b;(b=f.userName)?b=b.call(a,{hash:{},data:d}):(b=a&&a.userName,b="function"===typeof b?b.call(a,{hash:{},data:d}):b);c+=e(b)+"</a></div>\n    ";if((b=f["if"].call(a,a&&a.firstMessage,{hash:{},inverse:this.noop,fn:this.program(7,function(a,b){var c,d;c='<div class="first-message"><a href="javascript:void(0);" title="';(d=f.firstMessage)?
d=d.call(a,{hash:{},data:b}):(d=a&&a.firstMessage,d="function"===typeof d?d.call(a,{hash:{},data:b}):d);c+=e(d)+'">';(d=f.firstMessagePreview)?d=d.call(a,{hash:{},data:b}):(d=a&&a.firstMessagePreview,d="function"===typeof d?d.call(a,{hash:{},data:b}):d);return c+=e(d)+"</a></div>"},d),data:d}))||0===b)c+=b;c+='\n</td>\n<td class="visitor">\n    <div class="default-thread-controls inline-block">\n        ';if((b=f["if"].call(a,a&&a.canOpen,{hash:{},inverse:this.noop,fn:this.program(9,function(a,b){var c,
d,h;return c=""+('\n            <div class="control open-dialog open-control inline-block" title="'+e((d=f.l10n||a&&a.l10n,h={hash:{},data:b},d?d.call(a,"Click to chat with the visitor",h):g.call(a,"l10n","Click to chat with the visitor",h)))+'"></div>\n        ')},d),data:d}))||0===b)c+=b;c+="\n        ";if((b=f["if"].call(a,a&&a.canView,{hash:{},inverse:this.noop,fn:this.program(11,function(a,b){var c,d,h;return c=""+('\n            <div class="control view-control inline-block" title="'+e((d=f.l10n||
a&&a.l10n,h={hash:{},data:b},d?d.call(a,"Watch the chat",h):g.call(a,"l10n","Watch the chat",h)))+'"></div>\n        ')},d),data:d}))||0===b)c+=b;c+="\n        ";if((b=f["if"].call(a,a&&a.tracked,{hash:{},inverse:this.noop,fn:this.program(13,function(a,b){var c,d,h;return c=""+('\n            <div class="control track-control inline-block" title="'+e((d=f.l10n||a&&a.l10n,h={hash:{},data:b},d?d.call(a,"Tracked visitor's path",h):g.call(a,"l10n","Tracked visitor's path",h)))+'"></div>\n        ')},
d),data:d}))||0===b)c+=b;c+="\n        ";if((b=f["if"].call(a,a&&a.canBan,{hash:{},inverse:this.noop,fn:this.program(15,function(a,b){var c,d,h;return c=""+('\n            <div class="control ban-control inline-block" title="'+e((d=f.l10n||a&&a.l10n,h={hash:{},data:b},d?d.call(a,"Ban this visitor",h):g.call(a,"l10n","Ban this visitor",h)))+'"></div>\n        ')},d),data:d}))||0===b)c+=b;c+='\n    </div>\n    <div class="thread-controls inline-block"></div>\n</td>\n<td class="visitor">';if((b=f["if"].call(a,
a&&a.userIp,{hash:{},inverse:this.program(19,function(a,b){var c;(c=f.remote)?c=c.call(a,{hash:{},data:b}):(c=a&&a.remote,c="function"===typeof c?c.call(a,{hash:{},data:b}):c);return e(c)},d),fn:this.program(17,function(a,c){var b,d;b='<a href="javascript:void(0);" class="geo-link" title="GeoLocation">';(d=f.remote)?d=d.call(a,{hash:{},data:c}):(d=a&&a.remote,d="function"===typeof d?d.call(a,{hash:{},data:c}):d);return b+=e(d)+"</a>"},d),data:d}))||0===b)c+=b;c+='</td>\n<td class="visitor">';(b=f.stateDesc)?
b=b.call(a,{hash:{},data:d}):(b=a&&a.stateDesc,b="function"===typeof b?b.call(a,{hash:{},data:d}):b);c+=e(b)+'</td>\n<td class="visitor">';(b=f.agentName)?b=b.call(a,{hash:{},data:d}):(b=a&&a.agentName,b="function"===typeof b?b.call(a,{hash:{},data:d}):b);c+=e(b)+'</td>\n<td class="visitor"><span class="timesince" data-timestamp="';(b=f.totalTime)?b=b.call(a,{hash:{},data:d}):(b=a&&a.totalTime,b="function"===typeof b?b.call(a,{hash:{},data:d}):b);c+=e(b)+'"></span></td>\n<td class="visitor">';if((b=
f.unless.call(a,a&&a.chatting,{hash:{},inverse:this.program(23,function(a,c){return"-"},d),fn:this.program(21,function(a,c){var b,d;b='<span class="timesince" data-timestamp="';(d=f.waitingTime)?d=d.call(a,{hash:{},data:c}):(d=a&&a.waitingTime,d="function"===typeof d?d.call(a,{hash:{},data:c}):d);return b+=e(d)+'"></span>'},d),data:d}))||0===b)c+=b;c+='</td>\n<td class="visitor">';if((b=f["if"].call(a,a&&a.ban,{hash:{},inverse:this.program(27,function(a,c){var b;(b=f.userAgent)?b=b.call(a,{hash:{},
data:c}):(b=a&&a.userAgent,b="function"===typeof b?b.call(a,{hash:{},data:c}):b);return e(b)},d),fn:this.program(25,function(a,b){var c;return e((c=(c=a&&a.ban,null==c||!1===c?c:c.reason),"function"===typeof c?c.apply(a):c))},d),data:d}))||0===b)c+=b;return c+"</td>"});m.status_panel=l(function(c,a,f,b,d){this.compilerInfo=[4,">= 1.0.0"];f=this.merge(f,c.helpers);d=d||{};var g=f.helperMissing,e=this.escapeExpression;c='<div id="connstatus">';(b=f.message)?b=b.call(a,{hash:{},data:d}):(b=a&&a.message,
b="function"===typeof b?b.call(a,{hash:{},data:d}):b);c+=e(b);if((b=f["if"].call(a,(b=a&&a.agent,null==b||!1===b?b:b.away),{hash:{},inverse:this.program(3,function(a,c){var b,d;return e((b=f.l10n||a&&a.l10n,d={hash:{},data:c},b?b.call(a,"Up to date",d):g.call(a,"l10n","Up to date",d)))},d),fn:this.program(1,function(a,c){var b,d;return e((b=f.l10n||a&&a.l10n,d={hash:{},data:c},b?b.call(a,"Away",d):g.call(a,"l10n","Away",d)))},d),data:d}))||0===b)c+=b;c+='</div><div id="connlinks"><a href="javascript:void(0);" id="change-status">';
if((b=f["if"].call(a,(b=a&&a.agent,null==b||!1===b?b:b.away),{hash:{},inverse:this.program(7,function(a,c){var b,d;return e((b=f.l10n||a&&a.l10n,d={hash:{},data:c},b?b.call(a,'Set status as "Away"',d):g.call(a,"l10n",'Set status as "Away"',d)))},d),fn:this.program(5,function(a,c){var b,d;return e((b=f.l10n||a&&a.l10n,d={hash:{},data:c},b?b.call(a,'Set status as "Available"',d):g.call(a,"l10n",'Set status as "Available"',d)))},d),data:d}))||0===b)c+=b;return c+"</a></div>"});m.threads_collection=l(function(c,
a,f,b,d){this.compilerInfo=[4,">= 1.0.0"];f=this.merge(f,c.helpers);d=d||{};var g,e;c=f.helperMissing;b=this.escapeExpression;return a=""+('<table class="awaiting" border="0">\n<thead>\n<tr>\n    <th class="first">'+b((g=f.l10n||a&&a.l10n,e={hash:{},data:d},g?g.call(a,"Name",e):c.call(a,"l10n","Name",e)))+"</th>\n    <th>"+b((g=f.l10n||a&&a.l10n,e={hash:{},data:d},g?g.call(a,"Actions",e):c.call(a,"l10n","Actions",e)))+"</th>\n    <th>"+b((g=f.l10n||a&&a.l10n,e={hash:{},data:d},g?g.call(a,"Visitor's address",
e):c.call(a,"l10n","Visitor's address",e)))+"</th>\n    <th>"+b((g=f.l10n||a&&a.l10n,e={hash:{},data:d},g?g.call(a,"State",e):c.call(a,"l10n","State",e)))+"</th>\n    <th>"+b((g=f.l10n||a&&a.l10n,e={hash:{},data:d},g?g.call(a,"Operator",e):c.call(a,"l10n","Operator",e)))+"</th>\n    <th>"+b((g=f.l10n||a&&a.l10n,e={hash:{},data:d},g?g.call(a,"Total time",e):c.call(a,"l10n","Total time",e)))+"</th>\n    <th>"+b((g=f.l10n||a&&a.l10n,e={hash:{},data:d},g?g.call(a,"Waiting time",e):c.call(a,"l10n","Waiting time",
e)))+"</th>\n    <th>"+b((g=f.l10n||a&&a.l10n,e={hash:{},data:d},g?g.call(a,"Misc",e):c.call(a,"l10n","Misc",e)))+'</th>\n</tr>\n</thead>\n<tbody id="threads-container">\n\n</tbody>\n</table>')})})();
